// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oroox.SubSuppliers.Domain;

namespace Oroox.SubSuppliers.Domain.Migrations
{
    [DbContext(typeof(SubSuppliersContext))]
    [Migration("20210516160557_Customer")]
    partial class Customer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.Property<Guid>("CertificationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CertificationsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("CertificationCustomer");
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OtherTechnologiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomersId", "OtherTechnologiesId");

                    b.HasIndex("OtherTechnologiesId");

                    b.ToTable("CustomerOtherTechnology");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("Certification");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e486e819-13a2-459c-8e7e-e4781b12762c"),
                            Name = "ISO9001",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("8f0150b6-74d0-4a76-91d8-91a82982ba37"),
                            Name = "ISO14001",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("12eb82b9-5904-4700-884d-b5e76d7e79df"),
                            Name = "ISO13485",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("fef87ef3-02bd-446a-a45d-ab42c0261811"),
                            Name = "ITAF16949",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("a08a622c-d0c5-40b2-bda5-bd07b94748af"),
                            Name = "EN9100",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("6e384532-949e-4a67-b986-547e30fed394"),
                            Name = "Other",
                            Value = 5
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid?>("AddressTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CountryCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("CountryCodeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanySizeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanySizeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageAndFastestLeadTimeMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageAndFastestLeadTimeTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageWorkingHoursPerWeek")
                        .HasColumnType("float");

                    b.Property<bool?>("CanUseStepFiles")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialCharacteristics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTolerances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkingShiftsPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerAdditionalInfo");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("AddressType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c66d834b-6377-441f-a38d-007f95c53e28"),
                            Name = "Shipping",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("51777485-f6a0-45c3-a2e0-f261b90ecabd"),
                            Name = "Billing",
                            Value = 1
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("CompanySize");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51eb2321-b462-44c0-bd36-9d5aace2f860"),
                            Name = "LessThan10",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("72382fc5-bf8d-42a4-af23-5b1d6d737f08"),
                            Name = "LessThan25",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("e4cfa28a-f569-4a0e-a3ff-ab2ecec9fa0f"),
                            Name = "LessThan50",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("14fe8aa4-4f3f-4498-a00c-eba12ebe531a"),
                            Name = "LessThan100",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("0a5a83f0-f138-4ecd-8cb9-0b004dcc6c1c"),
                            Name = "MoreThan100",
                            Value = 101
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("CountryCode");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1253353-860c-470f-a039-72a2b05a02bd"),
                            Name = "AF",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("808d1253-4f63-4d9f-817e-7cdf306e73b0"),
                            Name = "AX",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("75aa9bed-ac0e-4ccc-bf72-5b8d67a49c15"),
                            Name = "AL",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("67067674-3835-47fd-a726-85322f421f35"),
                            Name = "DZ",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("dbc3f25e-41bf-43eb-b006-86d44f47ca99"),
                            Name = "AS",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("d37f6880-b350-4d55-a95e-96ad276b1352"),
                            Name = "AD",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("10989252-9639-4fe2-b26f-dec0d85b5c08"),
                            Name = "AO",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("44727a85-84fe-4043-9319-458df8cb90e2"),
                            Name = "AI",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("4dd2b8fa-aefe-4c6e-a315-95d8b0befa08"),
                            Name = "AQ",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("52f3fe37-86e2-4f05-8afd-9bda30123b18"),
                            Name = "AG",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("7f369fb8-9f08-47c4-aaae-02fd78ca0e1b"),
                            Name = "AR",
                            Value = 11
                        },
                        new
                        {
                            Id = new Guid("13866008-fe73-4085-b207-df7aeb4ef793"),
                            Name = "AM",
                            Value = 12
                        },
                        new
                        {
                            Id = new Guid("6d086eda-7de5-4947-8d5b-23a05454dc04"),
                            Name = "AW",
                            Value = 13
                        },
                        new
                        {
                            Id = new Guid("b9216e26-180c-48d0-b1b3-508289acaa5f"),
                            Name = "AU",
                            Value = 14
                        },
                        new
                        {
                            Id = new Guid("db3953aa-4660-42ae-9f91-1d85eb4168ae"),
                            Name = "AT",
                            Value = 15
                        },
                        new
                        {
                            Id = new Guid("7b07ec86-fc1a-4b0a-9077-08e39a3890d5"),
                            Name = "AZ",
                            Value = 16
                        },
                        new
                        {
                            Id = new Guid("92ec9d9f-d51b-4357-8d06-ed92b63e1c82"),
                            Name = "BS",
                            Value = 17
                        },
                        new
                        {
                            Id = new Guid("bf0916b4-41e0-44a4-ab63-0e7752b00234"),
                            Name = "BH",
                            Value = 18
                        },
                        new
                        {
                            Id = new Guid("27d68970-6e88-432b-aea1-1e331b2e4f95"),
                            Name = "BD",
                            Value = 19
                        },
                        new
                        {
                            Id = new Guid("2da7bfc3-69b1-4066-9387-2c12bf8bafea"),
                            Name = "BB",
                            Value = 20
                        },
                        new
                        {
                            Id = new Guid("23841bbd-d329-4c0a-a82c-8261e940a588"),
                            Name = "BY",
                            Value = 21
                        },
                        new
                        {
                            Id = new Guid("85daa31a-c721-49da-aeef-ff8df4e7dce8"),
                            Name = "BE",
                            Value = 22
                        },
                        new
                        {
                            Id = new Guid("84ab3828-e368-4287-abef-f90616916606"),
                            Name = "BZ",
                            Value = 23
                        },
                        new
                        {
                            Id = new Guid("155e9cd8-2d4d-401c-892e-a95c13f9b89b"),
                            Name = "BJ",
                            Value = 24
                        },
                        new
                        {
                            Id = new Guid("c5d03cb2-a2d1-4088-97bc-ec694866e9ff"),
                            Name = "BM",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("756f1c96-c85c-4044-8645-3cd1580c32c3"),
                            Name = "BT",
                            Value = 26
                        },
                        new
                        {
                            Id = new Guid("117d18c1-9f23-4977-96d2-46e568c3c8e9"),
                            Name = "BO",
                            Value = 27
                        },
                        new
                        {
                            Id = new Guid("e3b416a7-0868-4565-bf34-f05717f1bc06"),
                            Name = "BQ",
                            Value = 28
                        },
                        new
                        {
                            Id = new Guid("ce0aaf69-c06e-44fe-ba9d-67b3bc7d3e41"),
                            Name = "BA",
                            Value = 29
                        },
                        new
                        {
                            Id = new Guid("b6f13e00-b8a5-4d34-a8a3-e32243faf78c"),
                            Name = "BW",
                            Value = 30
                        },
                        new
                        {
                            Id = new Guid("0c7e32d5-3d6e-4ec6-80a8-05f5988b4de8"),
                            Name = "BV",
                            Value = 31
                        },
                        new
                        {
                            Id = new Guid("7c35632f-a972-41ff-bfb1-4f2d73666d3d"),
                            Name = "BR",
                            Value = 32
                        },
                        new
                        {
                            Id = new Guid("126314a7-831e-4d76-acbd-7c00d8fcbd97"),
                            Name = "IO",
                            Value = 33
                        },
                        new
                        {
                            Id = new Guid("2e490952-cb0e-4c83-baae-eb35cc87eb55"),
                            Name = "BN",
                            Value = 34
                        },
                        new
                        {
                            Id = new Guid("64952b9a-6dec-46f8-9bb5-720c2ddcba13"),
                            Name = "BG",
                            Value = 35
                        },
                        new
                        {
                            Id = new Guid("504fd77f-6d82-4ce2-b7ab-167d08a16604"),
                            Name = "BF",
                            Value = 36
                        },
                        new
                        {
                            Id = new Guid("e8f7cb10-a369-445c-b93d-1c3562c2f67a"),
                            Name = "BI",
                            Value = 37
                        },
                        new
                        {
                            Id = new Guid("eb702932-2f92-49bb-b098-d06597526056"),
                            Name = "CV",
                            Value = 38
                        },
                        new
                        {
                            Id = new Guid("db06edb2-7c85-484b-99b6-850295ca0b24"),
                            Name = "KH",
                            Value = 39
                        },
                        new
                        {
                            Id = new Guid("f0344ca8-d893-47a9-8600-6bfdfffde818"),
                            Name = "CM",
                            Value = 40
                        },
                        new
                        {
                            Id = new Guid("2fda1766-7f33-4961-aae7-e7a22b61e19e"),
                            Name = "CA",
                            Value = 41
                        },
                        new
                        {
                            Id = new Guid("7c71300d-e454-4fd6-8889-00b6484ca0b0"),
                            Name = "KY",
                            Value = 42
                        },
                        new
                        {
                            Id = new Guid("dcd55dba-06e6-4736-bf51-3c98ac91473f"),
                            Name = "CF",
                            Value = 43
                        },
                        new
                        {
                            Id = new Guid("d5eae9e3-a61e-4ea1-bd99-4397312e3463"),
                            Name = "TD",
                            Value = 44
                        },
                        new
                        {
                            Id = new Guid("48f45eab-d549-4486-895d-bd47d095b278"),
                            Name = "CL",
                            Value = 45
                        },
                        new
                        {
                            Id = new Guid("45db3d7b-9c1c-4043-9281-b77d08b4991b"),
                            Name = "CN",
                            Value = 46
                        },
                        new
                        {
                            Id = new Guid("5fa3cfdc-2c7a-4a23-9e30-7bc8ff4b2a19"),
                            Name = "CX",
                            Value = 47
                        },
                        new
                        {
                            Id = new Guid("2530f4b8-718a-491f-ac47-21485624faf5"),
                            Name = "CC",
                            Value = 48
                        },
                        new
                        {
                            Id = new Guid("c35954ba-688b-47a9-bd35-4839b177b93e"),
                            Name = "CO",
                            Value = 49
                        },
                        new
                        {
                            Id = new Guid("1fe09f59-c6cb-4ad7-9fe8-c9d3cce370b9"),
                            Name = "KM",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("1a2abbb1-b8f3-40e2-9950-2e0c4917613b"),
                            Name = "CG",
                            Value = 51
                        },
                        new
                        {
                            Id = new Guid("ff0fc2e9-1986-42bc-b178-6122e0545e10"),
                            Name = "CD",
                            Value = 52
                        },
                        new
                        {
                            Id = new Guid("3cd59a07-6859-4d8c-a442-5fc26aa3f221"),
                            Name = "CK",
                            Value = 53
                        },
                        new
                        {
                            Id = new Guid("52be9eca-5083-419c-b44f-f9567818742b"),
                            Name = "CR",
                            Value = 54
                        },
                        new
                        {
                            Id = new Guid("0c594c13-cbd3-4d43-bdca-fea439dde715"),
                            Name = "CI",
                            Value = 55
                        },
                        new
                        {
                            Id = new Guid("92fb8efc-a2c9-4c7d-8c21-60aa254e3909"),
                            Name = "HR",
                            Value = 56
                        },
                        new
                        {
                            Id = new Guid("7bfcf2c1-f392-4047-869e-427e2820fdcc"),
                            Name = "CU",
                            Value = 57
                        },
                        new
                        {
                            Id = new Guid("07e69fe0-d995-4891-b272-bacafe883c46"),
                            Name = "CW",
                            Value = 58
                        },
                        new
                        {
                            Id = new Guid("4f357f9c-730d-4e62-9104-19844b16d53d"),
                            Name = "CY",
                            Value = 59
                        },
                        new
                        {
                            Id = new Guid("91eec6c4-62b4-443e-a43b-f84988469b18"),
                            Name = "CZ",
                            Value = 60
                        },
                        new
                        {
                            Id = new Guid("62f72258-57e1-4331-b9e8-520244327f0e"),
                            Name = "DK",
                            Value = 61
                        },
                        new
                        {
                            Id = new Guid("ec00737b-17dd-440e-a27b-9594dd0fb701"),
                            Name = "DJ",
                            Value = 62
                        },
                        new
                        {
                            Id = new Guid("1834f6ec-5009-4997-98e2-614cbd71af6f"),
                            Name = "DM",
                            Value = 63
                        },
                        new
                        {
                            Id = new Guid("d2a753a0-2fc2-48f8-9129-c87e4e748ed5"),
                            Name = "DO",
                            Value = 64
                        },
                        new
                        {
                            Id = new Guid("ca9c2097-a452-4529-aea7-2e5d60a9d0bd"),
                            Name = "EC",
                            Value = 65
                        },
                        new
                        {
                            Id = new Guid("c341fc31-7f37-4ce1-acba-df0411c04c3c"),
                            Name = "EG",
                            Value = 66
                        },
                        new
                        {
                            Id = new Guid("311660f3-a5bf-43d5-890c-7d691e9ae548"),
                            Name = "SV",
                            Value = 67
                        },
                        new
                        {
                            Id = new Guid("91752b1d-5a36-4af1-b944-3ec6d5614f73"),
                            Name = "GQ",
                            Value = 68
                        },
                        new
                        {
                            Id = new Guid("25c15afd-a6cc-4511-996d-ef127efc3813"),
                            Name = "ER",
                            Value = 69
                        },
                        new
                        {
                            Id = new Guid("e255f40e-ade4-4f3b-9f82-90c12a71ca17"),
                            Name = "EE",
                            Value = 70
                        },
                        new
                        {
                            Id = new Guid("eb86c1e9-9d8a-46b1-bdae-936ea35b6e55"),
                            Name = "ET",
                            Value = 71
                        },
                        new
                        {
                            Id = new Guid("2ee4e0d1-74a6-4ea5-a2c8-e02d7b1be0c9"),
                            Name = "FK",
                            Value = 72
                        },
                        new
                        {
                            Id = new Guid("74dc9c90-bacd-4ae1-85c3-7277f8b440bc"),
                            Name = "FO",
                            Value = 73
                        },
                        new
                        {
                            Id = new Guid("7db7b81d-26c8-4f05-b061-c8e25a7b954e"),
                            Name = "FJ",
                            Value = 74
                        },
                        new
                        {
                            Id = new Guid("b071d73c-d1e5-4b03-b916-3c623cca02ad"),
                            Name = "FI",
                            Value = 75
                        },
                        new
                        {
                            Id = new Guid("1ad2da97-a7f7-4f87-a4ba-9ceb178f361c"),
                            Name = "FR",
                            Value = 76
                        },
                        new
                        {
                            Id = new Guid("26551d54-0d7a-4db7-add9-574bc465bad2"),
                            Name = "GF",
                            Value = 77
                        },
                        new
                        {
                            Id = new Guid("cb304971-77c8-4a3a-88e0-9c2bc614bb9f"),
                            Name = "PF",
                            Value = 78
                        },
                        new
                        {
                            Id = new Guid("4be3b368-3396-4721-9ac5-8a7730affffa"),
                            Name = "TF",
                            Value = 79
                        },
                        new
                        {
                            Id = new Guid("54231bed-a5c0-4d7c-a169-4c21d2271c46"),
                            Name = "GA",
                            Value = 80
                        },
                        new
                        {
                            Id = new Guid("97058246-edf1-434c-9416-8eed11f29466"),
                            Name = "GM",
                            Value = 81
                        },
                        new
                        {
                            Id = new Guid("00c0b052-217b-43a6-a07d-98d895296383"),
                            Name = "GE",
                            Value = 82
                        },
                        new
                        {
                            Id = new Guid("bdb5a9c1-c779-49e7-8076-945ec2547eb5"),
                            Name = "DE",
                            Value = 83
                        },
                        new
                        {
                            Id = new Guid("cbdf862f-af5d-47d8-af35-29a0ab68359c"),
                            Name = "GH",
                            Value = 84
                        },
                        new
                        {
                            Id = new Guid("c4225974-30ef-4601-8723-206b7923b5e2"),
                            Name = "GI",
                            Value = 85
                        },
                        new
                        {
                            Id = new Guid("6d8e4a52-3ca8-4f0a-b895-acef56eb766c"),
                            Name = "GR",
                            Value = 86
                        },
                        new
                        {
                            Id = new Guid("a2aaee53-f29d-46ab-8c50-bb6064cedac1"),
                            Name = "GL",
                            Value = 87
                        },
                        new
                        {
                            Id = new Guid("cb5b588f-4f6c-465e-9de7-ba92574845c5"),
                            Name = "GD",
                            Value = 88
                        },
                        new
                        {
                            Id = new Guid("c618d1c6-28d4-4234-9411-6e2a4525dfa2"),
                            Name = "GP",
                            Value = 89
                        },
                        new
                        {
                            Id = new Guid("6a79a5b5-057f-4103-a87c-fa12425a5d79"),
                            Name = "GU",
                            Value = 90
                        },
                        new
                        {
                            Id = new Guid("a6a7e21f-f1d1-4d17-a811-8102a5038fe5"),
                            Name = "GT",
                            Value = 91
                        },
                        new
                        {
                            Id = new Guid("c9ee39ef-59f6-44c0-9b4a-3affffb5d5c6"),
                            Name = "GG",
                            Value = 92
                        },
                        new
                        {
                            Id = new Guid("2c20e16d-f23b-4c1e-8388-c0f8a6ad46d9"),
                            Name = "GN",
                            Value = 93
                        },
                        new
                        {
                            Id = new Guid("ca00ed45-256d-438d-8352-8832d4e0fb3b"),
                            Name = "GW",
                            Value = 94
                        },
                        new
                        {
                            Id = new Guid("5b4bd2b6-4467-4b54-9601-15059c6043b2"),
                            Name = "GY",
                            Value = 95
                        },
                        new
                        {
                            Id = new Guid("42979981-ab02-4cf3-84ff-949e3ffa51a0"),
                            Name = "HT",
                            Value = 96
                        },
                        new
                        {
                            Id = new Guid("e67845ca-c206-40ab-84f3-5e7892fd3d61"),
                            Name = "HM",
                            Value = 97
                        },
                        new
                        {
                            Id = new Guid("a1119316-56fa-41c2-ba90-495fffbdf13d"),
                            Name = "VA",
                            Value = 98
                        },
                        new
                        {
                            Id = new Guid("953e7ea1-6e83-46bd-bf49-6882a372cd8c"),
                            Name = "HN",
                            Value = 99
                        },
                        new
                        {
                            Id = new Guid("5c173095-ec46-46b3-93b8-d392c9369093"),
                            Name = "HK",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("dcf0a977-1ee9-46c5-9150-8bb1461d3bcb"),
                            Name = "HU",
                            Value = 101
                        },
                        new
                        {
                            Id = new Guid("ae0c23fc-b6f8-47e6-bc93-510b6a56d15f"),
                            Name = "IS",
                            Value = 102
                        },
                        new
                        {
                            Id = new Guid("7fea8b1b-7664-4cfb-bb1a-9d3b19d089b2"),
                            Name = "IN",
                            Value = 103
                        },
                        new
                        {
                            Id = new Guid("a376a259-104b-4994-890f-fad5ff748346"),
                            Name = "ID",
                            Value = 104
                        },
                        new
                        {
                            Id = new Guid("e9767f56-ae55-4428-ae19-7c698da057c3"),
                            Name = "IR",
                            Value = 105
                        },
                        new
                        {
                            Id = new Guid("72c5697b-b4b4-48de-9a4b-622fcdbe3a24"),
                            Name = "IQ",
                            Value = 106
                        },
                        new
                        {
                            Id = new Guid("df0e0525-4b96-4881-8c85-0776c1268bee"),
                            Name = "IE",
                            Value = 107
                        },
                        new
                        {
                            Id = new Guid("4ff8e453-e71d-479b-823b-3efbbc79c676"),
                            Name = "IM",
                            Value = 108
                        },
                        new
                        {
                            Id = new Guid("5fc9ffe3-d141-40d2-885f-9f46827c2179"),
                            Name = "IL",
                            Value = 109
                        },
                        new
                        {
                            Id = new Guid("a7c348cc-11e8-476b-bc37-469d11b1cce7"),
                            Name = "IT",
                            Value = 110
                        },
                        new
                        {
                            Id = new Guid("c48279b3-c89c-4c7f-86c2-69d691c2c3c3"),
                            Name = "JM",
                            Value = 111
                        },
                        new
                        {
                            Id = new Guid("cde9a50e-877c-4acc-ab63-9ee5296a6668"),
                            Name = "JP",
                            Value = 112
                        },
                        new
                        {
                            Id = new Guid("e58e6dd6-736a-4bfb-b28d-0728a16b68e4"),
                            Name = "JE",
                            Value = 113
                        },
                        new
                        {
                            Id = new Guid("ccf6b61c-ae71-4720-884e-7ec3b98eccc6"),
                            Name = "JO",
                            Value = 114
                        },
                        new
                        {
                            Id = new Guid("93f640dd-af80-4805-b27a-9239714c1026"),
                            Name = "KZ",
                            Value = 115
                        },
                        new
                        {
                            Id = new Guid("44aa5075-7e49-4498-a622-333ff86f0195"),
                            Name = "KE",
                            Value = 116
                        },
                        new
                        {
                            Id = new Guid("837fc443-e1f5-4212-98e4-e7eb057d4fd3"),
                            Name = "KI",
                            Value = 117
                        },
                        new
                        {
                            Id = new Guid("7f8dc713-563b-41e9-8e4e-1b961e22a6a3"),
                            Name = "KP",
                            Value = 118
                        },
                        new
                        {
                            Id = new Guid("61521711-8373-4102-86b3-5edae59702c8"),
                            Name = "KR",
                            Value = 119
                        },
                        new
                        {
                            Id = new Guid("c9eadf71-2b2c-4007-88f3-eaa199d45302"),
                            Name = "KW",
                            Value = 120
                        },
                        new
                        {
                            Id = new Guid("232e7ca1-fa8c-42a4-a775-02b17d2d4414"),
                            Name = "KG",
                            Value = 121
                        },
                        new
                        {
                            Id = new Guid("5de73a11-c17c-4b7b-84a0-69b9ff753631"),
                            Name = "LA",
                            Value = 122
                        },
                        new
                        {
                            Id = new Guid("8b6882e3-ebc4-4146-a822-83c00eec7422"),
                            Name = "LV",
                            Value = 123
                        },
                        new
                        {
                            Id = new Guid("dd0062a4-32bc-429b-bb53-276a41bff398"),
                            Name = "LB",
                            Value = 124
                        },
                        new
                        {
                            Id = new Guid("9a53b9ee-33c5-4172-bf17-5aac3cbb9c24"),
                            Name = "LS",
                            Value = 125
                        },
                        new
                        {
                            Id = new Guid("40dcaccc-ab0e-4bbc-9463-ad05a78557c9"),
                            Name = "LR",
                            Value = 126
                        },
                        new
                        {
                            Id = new Guid("5118efb2-6bd0-4856-93a4-a0de0d1deff3"),
                            Name = "LY",
                            Value = 127
                        },
                        new
                        {
                            Id = new Guid("69bd156a-ca16-460a-98e5-62ca5de74057"),
                            Name = "LI",
                            Value = 128
                        },
                        new
                        {
                            Id = new Guid("4cfe1751-3189-4e3d-a1e6-7468db4806e7"),
                            Name = "LT",
                            Value = 129
                        },
                        new
                        {
                            Id = new Guid("57a68162-b2a5-4c49-beea-6f9d5da08383"),
                            Name = "LU",
                            Value = 130
                        },
                        new
                        {
                            Id = new Guid("1d5fc2aa-ef4b-46df-a56d-238802036db4"),
                            Name = "MO",
                            Value = 131
                        },
                        new
                        {
                            Id = new Guid("6ead0ca4-4c8a-414b-b3fb-0897344005f0"),
                            Name = "MK",
                            Value = 132
                        },
                        new
                        {
                            Id = new Guid("a641a8dc-60c8-4cf9-84b6-27178b864b99"),
                            Name = "MG",
                            Value = 133
                        },
                        new
                        {
                            Id = new Guid("293bcaaa-d0fe-47c5-a359-6803683b3601"),
                            Name = "MW",
                            Value = 134
                        },
                        new
                        {
                            Id = new Guid("07d00b6c-a0a4-4f47-9f0f-d89e72d556ef"),
                            Name = "MY",
                            Value = 135
                        },
                        new
                        {
                            Id = new Guid("1962f46a-b923-450e-9094-a62ff8822b6c"),
                            Name = "MV",
                            Value = 136
                        },
                        new
                        {
                            Id = new Guid("136507e5-e34a-416a-a560-42fbf6d8e887"),
                            Name = "ML",
                            Value = 137
                        },
                        new
                        {
                            Id = new Guid("760c949c-1593-463d-813e-422a60c26e71"),
                            Name = "MT",
                            Value = 138
                        },
                        new
                        {
                            Id = new Guid("8ecc9821-fb1a-491e-9ca1-ab4e88d9d1f8"),
                            Name = "MH",
                            Value = 139
                        },
                        new
                        {
                            Id = new Guid("e0e02f71-748c-4169-a81e-9009874ad840"),
                            Name = "MQ",
                            Value = 140
                        },
                        new
                        {
                            Id = new Guid("7180908e-883a-49aa-96a6-3c8971168595"),
                            Name = "MR",
                            Value = 141
                        },
                        new
                        {
                            Id = new Guid("d16fe58c-7500-488a-b2a1-7a85866cdb87"),
                            Name = "MU",
                            Value = 142
                        },
                        new
                        {
                            Id = new Guid("23754b88-17b2-4935-aa38-88a587349545"),
                            Name = "YT",
                            Value = 143
                        },
                        new
                        {
                            Id = new Guid("05f01001-c84a-40b9-818e-dcb227675e45"),
                            Name = "MX",
                            Value = 144
                        },
                        new
                        {
                            Id = new Guid("7e903a68-b07d-4f66-b9b1-92633755938f"),
                            Name = "FM",
                            Value = 145
                        },
                        new
                        {
                            Id = new Guid("b6d027b2-3283-4fce-8d88-f7eba5b6313b"),
                            Name = "MD",
                            Value = 146
                        },
                        new
                        {
                            Id = new Guid("885d8516-acff-43fa-a12c-f514594f7020"),
                            Name = "MC",
                            Value = 147
                        },
                        new
                        {
                            Id = new Guid("b37075c6-9c39-47eb-97d8-608d24814636"),
                            Name = "MN",
                            Value = 148
                        },
                        new
                        {
                            Id = new Guid("c5148c5e-e7f1-4b94-ae97-75758025d35c"),
                            Name = "ME",
                            Value = 149
                        },
                        new
                        {
                            Id = new Guid("9fea5c44-5d50-4e0a-9005-68cd2c426a03"),
                            Name = "MS",
                            Value = 150
                        },
                        new
                        {
                            Id = new Guid("4b9e7426-3e8f-47b7-9229-ae06a8712d51"),
                            Name = "MA",
                            Value = 151
                        },
                        new
                        {
                            Id = new Guid("f3fa947c-6e39-45cd-981c-8ab968a68268"),
                            Name = "MZ",
                            Value = 152
                        },
                        new
                        {
                            Id = new Guid("7d6e2c79-5b4e-4bc4-a5b9-c709a94429b1"),
                            Name = "MM",
                            Value = 153
                        },
                        new
                        {
                            Id = new Guid("893fd04d-9709-427d-a4cb-a13cbb9189f8"),
                            Name = "NA",
                            Value = 154
                        },
                        new
                        {
                            Id = new Guid("ad144153-67a8-44d3-9894-bdf87809249e"),
                            Name = "NR",
                            Value = 155
                        },
                        new
                        {
                            Id = new Guid("079314c7-b064-4bb4-b0db-6935d2954b35"),
                            Name = "NP",
                            Value = 156
                        },
                        new
                        {
                            Id = new Guid("fb1a64ec-3704-4394-a6b4-fb8c31ea2a3a"),
                            Name = "NL",
                            Value = 157
                        },
                        new
                        {
                            Id = new Guid("313c7132-b3f0-403a-ae5b-b8465e61eb60"),
                            Name = "NC",
                            Value = 158
                        },
                        new
                        {
                            Id = new Guid("0ea1f9e0-6d76-4fab-bccd-296adfc4ddf4"),
                            Name = "NZ",
                            Value = 159
                        },
                        new
                        {
                            Id = new Guid("bd67787f-36e6-4aba-a712-56bc4b0858b0"),
                            Name = "NI",
                            Value = 160
                        },
                        new
                        {
                            Id = new Guid("3bc41b93-8980-488a-845e-f91962c37110"),
                            Name = "NE",
                            Value = 161
                        },
                        new
                        {
                            Id = new Guid("a90a6843-86bf-4639-8f47-2de31816ad43"),
                            Name = "NG",
                            Value = 162
                        },
                        new
                        {
                            Id = new Guid("38e4bd72-f335-4b12-931b-dd53da7c71ce"),
                            Name = "NU",
                            Value = 163
                        },
                        new
                        {
                            Id = new Guid("5446a7c9-f000-41e3-8258-1e94d689c164"),
                            Name = "NF",
                            Value = 164
                        },
                        new
                        {
                            Id = new Guid("fab66fa4-8376-46e7-9836-ee42e79ea667"),
                            Name = "MP",
                            Value = 165
                        },
                        new
                        {
                            Id = new Guid("17645a3e-9845-4b02-9371-0d4e57d629e0"),
                            Name = "NO",
                            Value = 166
                        },
                        new
                        {
                            Id = new Guid("55f081ab-a0d2-4fc2-a86b-6dd998a2cc60"),
                            Name = "OM",
                            Value = 167
                        },
                        new
                        {
                            Id = new Guid("ab704cc6-587a-4d10-b60a-3fe3172a74b0"),
                            Name = "PK",
                            Value = 168
                        },
                        new
                        {
                            Id = new Guid("2c6b7433-03b4-4260-8111-e80f021390cd"),
                            Name = "PW",
                            Value = 169
                        },
                        new
                        {
                            Id = new Guid("adff0195-badb-4e5e-8568-d10915455d7e"),
                            Name = "PS",
                            Value = 170
                        },
                        new
                        {
                            Id = new Guid("5f7c074d-a925-490d-afcf-75925c601572"),
                            Name = "PA",
                            Value = 171
                        },
                        new
                        {
                            Id = new Guid("c58634a5-4dcd-410b-8f65-afe002caa91d"),
                            Name = "PG",
                            Value = 172
                        },
                        new
                        {
                            Id = new Guid("56ab3575-a84a-493c-b129-7c3c8cbb8ffc"),
                            Name = "PY",
                            Value = 173
                        },
                        new
                        {
                            Id = new Guid("84669a06-217c-4cdf-9748-cb7f0c773482"),
                            Name = "PE",
                            Value = 174
                        },
                        new
                        {
                            Id = new Guid("eaef52db-182a-4f94-b576-f7996207a601"),
                            Name = "PH",
                            Value = 175
                        },
                        new
                        {
                            Id = new Guid("66cac703-9c7b-4165-9fa5-6d375d813336"),
                            Name = "PN",
                            Value = 176
                        },
                        new
                        {
                            Id = new Guid("11cbea98-c64c-425d-8c17-7ebe1dcbee54"),
                            Name = "PL",
                            Value = 177
                        },
                        new
                        {
                            Id = new Guid("e9b4ce16-7c18-4eb8-8258-c0281700f9b4"),
                            Name = "PT",
                            Value = 178
                        },
                        new
                        {
                            Id = new Guid("dfc1bf2f-09e8-4a64-bf29-95e1c07608e9"),
                            Name = "PR",
                            Value = 179
                        },
                        new
                        {
                            Id = new Guid("227bd314-b71f-4826-b41c-bd73669c976d"),
                            Name = "QA",
                            Value = 180
                        },
                        new
                        {
                            Id = new Guid("f2a75e3c-6563-44fd-ba1f-02a9d667b090"),
                            Name = "RE",
                            Value = 181
                        },
                        new
                        {
                            Id = new Guid("f9beb256-18aa-4234-ac3f-c7734e1f8695"),
                            Name = "RO",
                            Value = 182
                        },
                        new
                        {
                            Id = new Guid("15d58600-2e48-4b99-ae0b-230415143b58"),
                            Name = "RU",
                            Value = 183
                        },
                        new
                        {
                            Id = new Guid("804b067f-2c35-43d5-9bb2-72c8a861cfa5"),
                            Name = "RW",
                            Value = 184
                        },
                        new
                        {
                            Id = new Guid("e01f840d-3e05-43f2-a37e-1eb72fc209ef"),
                            Name = "BL",
                            Value = 185
                        },
                        new
                        {
                            Id = new Guid("029da9d2-1e6b-439b-9c43-543c641df425"),
                            Name = "SH",
                            Value = 186
                        },
                        new
                        {
                            Id = new Guid("fb54deb4-a710-4d92-a00a-a49afd12b297"),
                            Name = "KN",
                            Value = 187
                        },
                        new
                        {
                            Id = new Guid("45f024d4-63c0-4508-8aae-b13721d74ba1"),
                            Name = "LC",
                            Value = 188
                        },
                        new
                        {
                            Id = new Guid("265558a4-2997-4237-9e1f-2b52e1530ddd"),
                            Name = "MF",
                            Value = 189
                        },
                        new
                        {
                            Id = new Guid("169fe1a9-a335-4655-8168-20394dd4ec70"),
                            Name = "PM",
                            Value = 190
                        },
                        new
                        {
                            Id = new Guid("ea636b70-4b95-4730-8914-8390b061bb10"),
                            Name = "VC",
                            Value = 191
                        },
                        new
                        {
                            Id = new Guid("9441f4c5-bb89-4a14-87dc-07337c95420d"),
                            Name = "WS",
                            Value = 192
                        },
                        new
                        {
                            Id = new Guid("2a9a2052-a005-4519-8dbc-4fd28a166190"),
                            Name = "SM",
                            Value = 193
                        },
                        new
                        {
                            Id = new Guid("a8900e96-8822-46a7-8e9b-e93b2ef7e06a"),
                            Name = "ST",
                            Value = 194
                        },
                        new
                        {
                            Id = new Guid("3d11dbcd-3c89-4ee9-bbe6-d75758db88ef"),
                            Name = "SA",
                            Value = 195
                        },
                        new
                        {
                            Id = new Guid("6d7ed103-80d6-4ca3-bb26-8e9c12743891"),
                            Name = "SN",
                            Value = 196
                        },
                        new
                        {
                            Id = new Guid("57f30592-a2c1-4006-b14a-c3536b116eab"),
                            Name = "RS",
                            Value = 197
                        },
                        new
                        {
                            Id = new Guid("71fcbc12-27e7-4ea4-a7a7-b7b9fc0f2b90"),
                            Name = "SC",
                            Value = 198
                        },
                        new
                        {
                            Id = new Guid("e1c2ee86-96ce-4652-a177-2e55e9eae2b6"),
                            Name = "SL",
                            Value = 199
                        },
                        new
                        {
                            Id = new Guid("cecd3b33-ca6a-4ae3-ad48-4e2c6920ded2"),
                            Name = "SG",
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("b32ef298-46aa-4935-b382-f89bb74a56a8"),
                            Name = "SX",
                            Value = 201
                        },
                        new
                        {
                            Id = new Guid("3bd3daef-72ba-4e24-8fb0-23d1f9573234"),
                            Name = "SK",
                            Value = 202
                        },
                        new
                        {
                            Id = new Guid("3ede45e1-75a8-44f7-89f5-d82eec726cb0"),
                            Name = "SI",
                            Value = 203
                        },
                        new
                        {
                            Id = new Guid("2b5997d4-fed8-4d84-8e9a-7155f0f6e30f"),
                            Name = "SB",
                            Value = 204
                        },
                        new
                        {
                            Id = new Guid("9bc5e60a-5bea-4d44-9ef4-e47a38375d89"),
                            Name = "SO",
                            Value = 205
                        },
                        new
                        {
                            Id = new Guid("b0720023-38b1-4755-bf17-8df25af0b563"),
                            Name = "ZA",
                            Value = 206
                        },
                        new
                        {
                            Id = new Guid("793ccced-594e-49a9-bb9e-dd14846743a7"),
                            Name = "GS",
                            Value = 207
                        },
                        new
                        {
                            Id = new Guid("4305f445-f71e-4431-aae8-af17c142f0fe"),
                            Name = "SS",
                            Value = 208
                        },
                        new
                        {
                            Id = new Guid("d19bd931-6f0c-4385-922e-60b80911c3c3"),
                            Name = "ES",
                            Value = 209
                        },
                        new
                        {
                            Id = new Guid("2ddee2d6-2837-4fc9-ba2f-3f96d8ad3f96"),
                            Name = "LK",
                            Value = 210
                        },
                        new
                        {
                            Id = new Guid("70aab969-07b3-44df-a9a0-b0bc377882ba"),
                            Name = "SD",
                            Value = 211
                        },
                        new
                        {
                            Id = new Guid("2d88a249-d595-4119-96ec-a4f49060f11c"),
                            Name = "SR",
                            Value = 212
                        },
                        new
                        {
                            Id = new Guid("492bbfe4-a958-4d30-b381-2d6e4e85c4e3"),
                            Name = "SJ",
                            Value = 213
                        },
                        new
                        {
                            Id = new Guid("ac4a97b0-cccf-4270-bd95-e3f8633d1849"),
                            Name = "SZ",
                            Value = 214
                        },
                        new
                        {
                            Id = new Guid("44d41499-24b2-454b-8872-7fd8f97977f0"),
                            Name = "SE",
                            Value = 215
                        },
                        new
                        {
                            Id = new Guid("09d4c394-aeda-4568-86f3-796c8aa0ac0a"),
                            Name = "CH",
                            Value = 216
                        },
                        new
                        {
                            Id = new Guid("9668f8e8-cc35-42b1-adc7-4451e930950e"),
                            Name = "SY",
                            Value = 217
                        },
                        new
                        {
                            Id = new Guid("3ee870be-f63a-4d12-a3b4-26f3a63b7b2f"),
                            Name = "TW",
                            Value = 218
                        },
                        new
                        {
                            Id = new Guid("4ddb0bc7-ff82-461a-bd9e-b5954e270c84"),
                            Name = "TJ",
                            Value = 219
                        },
                        new
                        {
                            Id = new Guid("ca11ce7d-b0e5-4046-b8a0-f6f6c780ba7a"),
                            Name = "TZ",
                            Value = 220
                        },
                        new
                        {
                            Id = new Guid("2be9a338-276f-4978-98c8-041643880440"),
                            Name = "TH",
                            Value = 221
                        },
                        new
                        {
                            Id = new Guid("1b0927f6-a0ed-4625-861b-79803bee3147"),
                            Name = "TL",
                            Value = 222
                        },
                        new
                        {
                            Id = new Guid("c31fedc6-356e-4192-94e3-2606b1084b70"),
                            Name = "TG",
                            Value = 223
                        },
                        new
                        {
                            Id = new Guid("3f978f0b-6590-4742-801e-a95156a9f27d"),
                            Name = "TK",
                            Value = 224
                        },
                        new
                        {
                            Id = new Guid("46f5093c-640b-4d21-8a9e-c4384039e347"),
                            Name = "TO",
                            Value = 225
                        },
                        new
                        {
                            Id = new Guid("7f7ac097-b4de-4b00-be19-ac08e2c631b3"),
                            Name = "TT",
                            Value = 226
                        },
                        new
                        {
                            Id = new Guid("67baafbd-3f2c-4168-a08b-b2593d5ed770"),
                            Name = "TN",
                            Value = 227
                        },
                        new
                        {
                            Id = new Guid("c6e090dd-626e-4980-9751-5adfe3085383"),
                            Name = "TR",
                            Value = 228
                        },
                        new
                        {
                            Id = new Guid("2e388040-2009-463f-a02d-3031d81273b7"),
                            Name = "TM",
                            Value = 229
                        },
                        new
                        {
                            Id = new Guid("543d9145-b121-4687-9741-4b74e8b15b0f"),
                            Name = "TC",
                            Value = 230
                        },
                        new
                        {
                            Id = new Guid("e0572937-c553-4ecb-bc71-4cb05eca8118"),
                            Name = "TV",
                            Value = 231
                        },
                        new
                        {
                            Id = new Guid("24870ad2-b99e-4871-a8ed-18169be90bc7"),
                            Name = "UG",
                            Value = 232
                        },
                        new
                        {
                            Id = new Guid("d7cf4e28-11a0-40ea-9681-dab31b02c4a4"),
                            Name = "UA",
                            Value = 233
                        },
                        new
                        {
                            Id = new Guid("dbd6ea82-49d6-422b-8b4a-7c511b54ed65"),
                            Name = "AE",
                            Value = 234
                        },
                        new
                        {
                            Id = new Guid("a25d4518-47d0-48fb-8229-14944135ade2"),
                            Name = "GB",
                            Value = 235
                        },
                        new
                        {
                            Id = new Guid("b823f938-3811-430c-b7f2-7ec096499d6f"),
                            Name = "US",
                            Value = 236
                        },
                        new
                        {
                            Id = new Guid("c12fae3e-2b06-456c-99cf-46bbd6ceb836"),
                            Name = "UM",
                            Value = 237
                        },
                        new
                        {
                            Id = new Guid("3b584d28-02db-4439-9502-dd8f6c61a64c"),
                            Name = "UY",
                            Value = 238
                        },
                        new
                        {
                            Id = new Guid("4c22885a-c098-4bb9-9d7e-8f9bc96999a6"),
                            Name = "UZ",
                            Value = 239
                        },
                        new
                        {
                            Id = new Guid("8cbf17d3-9425-40d3-9ce9-a0fc7e19aea2"),
                            Name = "VU",
                            Value = 240
                        },
                        new
                        {
                            Id = new Guid("fc46bb97-afab-4ba2-87c2-51e46a8ecdd1"),
                            Name = "VE",
                            Value = 241
                        },
                        new
                        {
                            Id = new Guid("72e53b3c-4e5f-40d0-bbf0-55b07a896590"),
                            Name = "VN",
                            Value = 242
                        },
                        new
                        {
                            Id = new Guid("4e91e9cd-2725-4d1a-8c36-24d1e169da01"),
                            Name = "VG",
                            Value = 243
                        },
                        new
                        {
                            Id = new Guid("bb3c65b7-3b2b-4879-8650-37f53aa79f4d"),
                            Name = "VI",
                            Value = 244
                        },
                        new
                        {
                            Id = new Guid("db484cbf-f370-4f0b-a946-6bba027b7cf5"),
                            Name = "WF",
                            Value = 245
                        },
                        new
                        {
                            Id = new Guid("899601b6-6ea2-4f46-9159-62b6640539c2"),
                            Name = "EH",
                            Value = 246
                        },
                        new
                        {
                            Id = new Guid("a26bb9d2-a365-4db7-8e3c-cd2d38612ca0"),
                            Name = "YE",
                            Value = 247
                        },
                        new
                        {
                            Id = new Guid("f4936197-3a64-4c2c-a35a-dfd9c293c66f"),
                            Name = "ZM",
                            Value = 248
                        },
                        new
                        {
                            Id = new Guid("ae396b4b-9520-4896-bc54-4af85c424fe4"),
                            Name = "ZW",
                            Value = 249
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("MachineDimensionsType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3c2e68ee-cc02-4d1d-9513-1ce73170fd3b"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("d806b7bf-6e4d-46fd-8d18-211cce2ebb9b"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("c8bc5a3c-bb74-4e5c-8c4f-499327aca240"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("MillingMachineType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecc185b6-57c9-4d50-bbfa-8971052a1afe"),
                            Name = "TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("a863b002-f736-463f-a124-4d718408fe06"),
                            Name = "TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("c4ded1cb-38a1-4983-a3dc-d8a2e0cff378"),
                            Name = "TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("86aae675-4121-4de7-84e6-e7c1a4cd72a4"),
                            Name = "TYPE_4",
                            Value = 3
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("OtherTechnology");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e069b824-f2ee-4a96-913a-5b0d99e8fef1"),
                            Name = "DeepHoleDrilling",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("b7342d24-94b0-4c6c-a5b4-e7eddd8a3fac"),
                            Name = "ThreadsM",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("bf45a958-2bca-437a-8756-a9741d920fd1"),
                            Name = "ThreadsTr",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("4f9287a2-5ce4-466f-a72f-34484b020170"),
                            Name = "Toothings",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("81abedbc-7822-4add-81bd-2eb6f2406f4b"),
                            Name = "Engravings",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("87e565f5-e0c7-44d5-b5fc-69a5e5ff16c0"),
                            Name = "LaserMarking",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("89b5d5f5-10ae-41dd-ac3f-7f608b6f774e"),
                            Name = "Knurling",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("d7c76506-d968-4afa-968f-82dccb6e83aa"),
                            Name = "Annealing",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("87336eb8-c54f-491f-b83d-d3576ecab4a4"),
                            Name = "Other",
                            Value = 8
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid?>("MillingMachineDimensionsTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("MillingMachineDimensionsTypeId");

                    b.ToTable("MillingMachine");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("MillingMachineDimensionsType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc1c59af-7c78-49ed-95b1-ae29cc181472"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("1205ef7c-df5a-454a-8070-3d158a097fa9"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("7ee4a09e-5fe3-46b9-9afd-72354a21243c"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TurningMachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TurningMachineTypeId");

                    b.ToTable("TurningMachine");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.TurningMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Value");

                    b.ToTable("TurningMachineType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0ea3b3c-1583-4509-9913-a09fe22f5e27"),
                            Name = "TURNING_MACHINE_TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("79000159-f5fc-4663-a050-2817cd31f72d"),
                            Name = "TURNING_MACHINE_TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("09dcb5cf-5288-4db4-a464-9b3f997ed23f"),
                            Name = "TURNING_MACHINE_TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("762e96ec-74bb-405d-ad2f-86dc60bcb02d"),
                            Name = "TURNING_MACHINE_TYPE_4",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("f82e6a4d-cd79-4fd9-b925-4352e2453f69"),
                            Name = "TURNING_MACHINE_TYPE_5",
                            Value = 4
                        });
                });

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", null)
                        .WithMany()
                        .HasForeignKey("OtherTechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", "AddressType")
                        .WithMany()
                        .HasForeignKey("AddressTypeId");

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCode", "CountryCode")
                        .WithMany()
                        .HasForeignKey("CountryCodeId");

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressType");

                    b.Navigation("CountryCode");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySize", "CompanySize")
                        .WithMany("Customers")
                        .HasForeignKey("CompanySizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySize");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithOne("CustomerAdditionalInfo")
                        .HasForeignKey("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("MillingMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", "MachineType")
                        .WithMany()
                        .HasForeignKey("MachineTypeId");

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", "MillingMachineDimensionsType")
                        .WithMany()
                        .HasForeignKey("MillingMachineDimensionsTypeId");

                    b.Navigation("Customer");

                    b.Navigation("MachineType");

                    b.Navigation("MillingMachineDimensionsType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("TurningMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.TurningMachineType", "TurningMachineType")
                        .WithMany()
                        .HasForeignKey("TurningMachineTypeId");

                    b.Navigation("Customer");

                    b.Navigation("TurningMachineType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerAdditionalInfo");

                    b.Navigation("MillingMachines");

                    b.Navigation("TurningMachines");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySize", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
