// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oroox.SubSuppliers.Domain.Context;

namespace Oroox.SubSuppliers.Domain.Migrations
{
    [DbContext(typeof(SubSuppliersContext))]
    [Migration("20210525112214_Customer")]
    partial class Customer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.Property<Guid>("CertificationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CertificationsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("CertificationCustomer");
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OtherTechnologiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomersId", "OtherTechnologiesId");

                    b.HasIndex("OtherTechnologiesId");

                    b.ToTable("CustomerOtherTechnology");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ad03a69-7f42-590f-92f1-f2000f533a9f"),
                            Name = "ISO9001",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("cac0fbe5-feab-577e-a502-63cb3af5cd50"),
                            Name = "ISO14001",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("e985886b-4e22-5a0b-95a0-d7db7b339139"),
                            Name = "ISO13485",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("c42d8176-3999-558c-93d0-3a0f49c9967e"),
                            Name = "ITAF16949",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("5dc24980-27b8-5899-a7db-6d9a434b07c9"),
                            Name = "EN9100",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("46cc9416-0e09-5790-8edf-1afd310798b8"),
                            Name = "Other",
                            Value = 5
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.ContactPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactPerson");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("AddressTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryCodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("CountryCodeTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanySizeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerAdditionalInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanySizeTypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageAndFastestLeadTimeMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageAndFastestLeadTimeTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageWorkingHoursPerWeek")
                        .HasColumnType("float");

                    b.Property<bool?>("CanUseStepFiles")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialCharacteristics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTolerances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkingShiftsPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerAdditionalInfo");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("AddressTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8883146-c906-5d1c-90b9-7de145f91345"),
                            Name = "Shipping",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("19795683-2de9-51cf-87b5-14e1b29a20cb"),
                            Name = "Billing",
                            Value = 1
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySizeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("CompanySizeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e497d944-64db-5ea5-8cc4-df29ce65a15e"),
                            Name = "LessThan10",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("88612e63-9606-5eec-963d-d376de208121"),
                            Name = "LessThan25",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("7ed405fa-6221-5ca1-bf00-ef024e66aa6e"),
                            Name = "LessThan50",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("03771842-6399-500e-a446-f0f090e2b45c"),
                            Name = "LessThan100",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("05594fee-a667-5523-9ad8-e7c5e6fd3a2a"),
                            Name = "MoreThan100",
                            Value = 101
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("CountryCodeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b912629-fa73-5570-8d2b-be9f75a46a05"),
                            Name = "AF",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("7521a246-a1cf-5159-85ac-c11ada8106b9"),
                            Name = "AX",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("3ed45125-61ab-50ca-be1b-5837942942ce"),
                            Name = "AL",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("e78525db-7915-5122-a712-af8cedbe6b31"),
                            Name = "DZ",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("fc1abc91-2fc1-54e1-b7f9-3f1f035b59bb"),
                            Name = "AS",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("48f9e04c-021c-5954-b9ee-eb0965f3afed"),
                            Name = "AD",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("d0658776-dbda-5820-bbfb-f4ec7253c3be"),
                            Name = "AO",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("ef6e1e8e-1cd7-5fd9-a504-67fada2b51d6"),
                            Name = "AI",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("62cd4ed3-2722-59e6-83b6-b4a889feb8b9"),
                            Name = "AQ",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("44216339-46df-5746-bb93-34cb127c8964"),
                            Name = "AG",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("2c4e284e-01b7-5ea8-9536-7535dad4fba2"),
                            Name = "AR",
                            Value = 11
                        },
                        new
                        {
                            Id = new Guid("aa9d8192-79d1-572a-b3e8-31367c44457b"),
                            Name = "AM",
                            Value = 12
                        },
                        new
                        {
                            Id = new Guid("aa20bdaa-5656-5381-b4a9-8f68934fe356"),
                            Name = "AW",
                            Value = 13
                        },
                        new
                        {
                            Id = new Guid("bc178c82-718d-548f-881c-37b863a8c58d"),
                            Name = "AU",
                            Value = 14
                        },
                        new
                        {
                            Id = new Guid("79a2d442-4c04-53d8-b5d7-88b56d5d8587"),
                            Name = "AT",
                            Value = 15
                        },
                        new
                        {
                            Id = new Guid("e2021c77-8e66-54c3-8c78-c5076d70b3c2"),
                            Name = "AZ",
                            Value = 16
                        },
                        new
                        {
                            Id = new Guid("1e65cb6b-dccc-5f16-9c9a-b73c96783555"),
                            Name = "BS",
                            Value = 17
                        },
                        new
                        {
                            Id = new Guid("1938c913-befa-58bc-b6f2-a772aad79dc3"),
                            Name = "BH",
                            Value = 18
                        },
                        new
                        {
                            Id = new Guid("95e9813e-2e2c-5aa4-840a-0f73d419441e"),
                            Name = "BD",
                            Value = 19
                        },
                        new
                        {
                            Id = new Guid("3c8c60ae-e838-5c5b-b757-0f86fdefd849"),
                            Name = "BB",
                            Value = 20
                        },
                        new
                        {
                            Id = new Guid("dedb88dd-cac1-5643-affc-92249dde4ca7"),
                            Name = "BY",
                            Value = 21
                        },
                        new
                        {
                            Id = new Guid("0acb7d7b-376b-581e-a2b6-674e9b16d3e9"),
                            Name = "BE",
                            Value = 22
                        },
                        new
                        {
                            Id = new Guid("69c91cd7-ea28-5dc2-9172-a8e6bc5bdb9c"),
                            Name = "BZ",
                            Value = 23
                        },
                        new
                        {
                            Id = new Guid("f9fe93a9-8141-57aa-a45b-5fff102118b1"),
                            Name = "BJ",
                            Value = 24
                        },
                        new
                        {
                            Id = new Guid("dd58c458-8cdc-525f-8c3a-33c1e2402591"),
                            Name = "BM",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("96ffb2ac-d3f6-5d6d-8525-eca3ebf2a0e1"),
                            Name = "BT",
                            Value = 26
                        },
                        new
                        {
                            Id = new Guid("f0b17b5a-249f-557e-bb30-dbdf5e462ddb"),
                            Name = "BO",
                            Value = 27
                        },
                        new
                        {
                            Id = new Guid("f9b1e638-f51b-515b-89d9-1e6fa1282b86"),
                            Name = "BQ",
                            Value = 28
                        },
                        new
                        {
                            Id = new Guid("537ad173-dbe4-5eb2-9e89-ce00e9743fcc"),
                            Name = "BA",
                            Value = 29
                        },
                        new
                        {
                            Id = new Guid("99d12c44-cb61-5bbd-8424-9f0314140770"),
                            Name = "BW",
                            Value = 30
                        },
                        new
                        {
                            Id = new Guid("7703d672-5dc7-5707-91c0-009afcefb72f"),
                            Name = "BV",
                            Value = 31
                        },
                        new
                        {
                            Id = new Guid("2fa5b328-cc3c-505e-88a8-c7051904cc6c"),
                            Name = "BR",
                            Value = 32
                        },
                        new
                        {
                            Id = new Guid("4c4e6920-08f3-5623-9662-a064df656906"),
                            Name = "IO",
                            Value = 33
                        },
                        new
                        {
                            Id = new Guid("e87ecdeb-4bf5-5171-a3b3-4439a3060614"),
                            Name = "BN",
                            Value = 34
                        },
                        new
                        {
                            Id = new Guid("63d2857b-bedd-5faf-bd0b-3bcbf45716a6"),
                            Name = "BG",
                            Value = 35
                        },
                        new
                        {
                            Id = new Guid("76c179cb-0ee9-5af2-bdcc-dbf99d1a5d86"),
                            Name = "BF",
                            Value = 36
                        },
                        new
                        {
                            Id = new Guid("bfe1b261-9d65-5109-93c2-ed1e16132358"),
                            Name = "BI",
                            Value = 37
                        },
                        new
                        {
                            Id = new Guid("feb126e1-3952-570d-b000-44905bbaebd3"),
                            Name = "CV",
                            Value = 38
                        },
                        new
                        {
                            Id = new Guid("598622b9-c16f-53a0-aabe-257520427da2"),
                            Name = "KH",
                            Value = 39
                        },
                        new
                        {
                            Id = new Guid("5d9739df-7180-5b8c-8baf-3f8ada982df0"),
                            Name = "CM",
                            Value = 40
                        },
                        new
                        {
                            Id = new Guid("41855dfa-628d-5649-80e1-ba3cbf53574e"),
                            Name = "CA",
                            Value = 41
                        },
                        new
                        {
                            Id = new Guid("32aa490f-bd1c-572d-bed4-0dd785b1dc63"),
                            Name = "KY",
                            Value = 42
                        },
                        new
                        {
                            Id = new Guid("08b574a7-fcbe-59b0-8227-ec1e5a278584"),
                            Name = "CF",
                            Value = 43
                        },
                        new
                        {
                            Id = new Guid("f28dc683-756e-5334-b776-a455b4bfba8d"),
                            Name = "TD",
                            Value = 44
                        },
                        new
                        {
                            Id = new Guid("fbeeca20-ed11-5094-ba09-1a43199869f9"),
                            Name = "CL",
                            Value = 45
                        },
                        new
                        {
                            Id = new Guid("452db218-a3fd-5bd8-8265-9b8d756e7fcc"),
                            Name = "CN",
                            Value = 46
                        },
                        new
                        {
                            Id = new Guid("b3018e30-9874-5262-b95e-4191f269d75c"),
                            Name = "CX",
                            Value = 47
                        },
                        new
                        {
                            Id = new Guid("d87c72b4-28b4-544f-aa1c-d362a1e61f99"),
                            Name = "CC",
                            Value = 48
                        },
                        new
                        {
                            Id = new Guid("99c34107-d0b8-5049-834a-cf6ecea0afa2"),
                            Name = "CO",
                            Value = 49
                        },
                        new
                        {
                            Id = new Guid("7ea12859-eea0-5c5c-a904-0478f8dcf73c"),
                            Name = "KM",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("15492e57-f3a2-57d9-9409-92b3fde60203"),
                            Name = "CG",
                            Value = 51
                        },
                        new
                        {
                            Id = new Guid("46de7fa0-77fe-52e1-b7d3-0a4fe022bcc3"),
                            Name = "CD",
                            Value = 52
                        },
                        new
                        {
                            Id = new Guid("57d64285-209f-5b24-b704-fdc1c7011ea3"),
                            Name = "CK",
                            Value = 53
                        },
                        new
                        {
                            Id = new Guid("d5ad3867-f97b-5ee6-bb51-03a0dcbbe865"),
                            Name = "CR",
                            Value = 54
                        },
                        new
                        {
                            Id = new Guid("885341ed-8c15-5247-95b4-fa1ce7030517"),
                            Name = "CI",
                            Value = 55
                        },
                        new
                        {
                            Id = new Guid("a2d51f38-bbc1-52b6-9f15-c82199513c6a"),
                            Name = "HR",
                            Value = 56
                        },
                        new
                        {
                            Id = new Guid("69f41139-eda8-55ae-acd8-065f360f625a"),
                            Name = "CU",
                            Value = 57
                        },
                        new
                        {
                            Id = new Guid("2cf0be4d-de25-5582-977b-b789b23d9801"),
                            Name = "CW",
                            Value = 58
                        },
                        new
                        {
                            Id = new Guid("ef618e7c-c48b-5f54-ae25-0b7ac9c1a8dd"),
                            Name = "CY",
                            Value = 59
                        },
                        new
                        {
                            Id = new Guid("09ed5917-efba-5440-aac1-55037ae268f8"),
                            Name = "CZ",
                            Value = 60
                        },
                        new
                        {
                            Id = new Guid("707c6f5e-0752-594f-95aa-ef4642711b71"),
                            Name = "DK",
                            Value = 61
                        },
                        new
                        {
                            Id = new Guid("28f62e86-2a1d-5204-b993-4c5b6bb8b5f6"),
                            Name = "DJ",
                            Value = 62
                        },
                        new
                        {
                            Id = new Guid("14cd47a8-b30b-5a19-8303-8b6c38f61629"),
                            Name = "DM",
                            Value = 63
                        },
                        new
                        {
                            Id = new Guid("a9436dd0-836e-5c4b-a5c0-341b1fb973e2"),
                            Name = "DO",
                            Value = 64
                        },
                        new
                        {
                            Id = new Guid("ef80d953-432d-5ada-a475-b75237d1d0fa"),
                            Name = "EC",
                            Value = 65
                        },
                        new
                        {
                            Id = new Guid("b2cef41b-4815-5428-a9ba-c4b490e08beb"),
                            Name = "EG",
                            Value = 66
                        },
                        new
                        {
                            Id = new Guid("0ef99452-1c18-521a-8b54-5a9684926548"),
                            Name = "SV",
                            Value = 67
                        },
                        new
                        {
                            Id = new Guid("b261bb15-9b3a-5786-95ef-d8e49967b52c"),
                            Name = "GQ",
                            Value = 68
                        },
                        new
                        {
                            Id = new Guid("c61112d0-6391-5772-a193-39c3ec915b5c"),
                            Name = "ER",
                            Value = 69
                        },
                        new
                        {
                            Id = new Guid("a02cc222-3f9d-561d-8945-db49b2f027e4"),
                            Name = "EE",
                            Value = 70
                        },
                        new
                        {
                            Id = new Guid("6d5d8583-95af-58fa-91a9-22a6f56d3af3"),
                            Name = "ET",
                            Value = 71
                        },
                        new
                        {
                            Id = new Guid("4149930c-28ff-55bb-b12d-f046314a4610"),
                            Name = "FK",
                            Value = 72
                        },
                        new
                        {
                            Id = new Guid("3a9b4818-daac-51d6-9c21-30f1255d389d"),
                            Name = "FO",
                            Value = 73
                        },
                        new
                        {
                            Id = new Guid("8e07f3fa-0ce2-5e50-b9a2-c841832be443"),
                            Name = "FJ",
                            Value = 74
                        },
                        new
                        {
                            Id = new Guid("8753c751-bb7b-5c25-a1f6-1d38bcbe52ba"),
                            Name = "FI",
                            Value = 75
                        },
                        new
                        {
                            Id = new Guid("30c019ea-d355-586e-8896-fea1e61a823e"),
                            Name = "FR",
                            Value = 76
                        },
                        new
                        {
                            Id = new Guid("0eddd99c-2630-5924-bc87-b1ec86956828"),
                            Name = "GF",
                            Value = 77
                        },
                        new
                        {
                            Id = new Guid("2fbf9894-4d7b-5381-8163-91c3db053c31"),
                            Name = "PF",
                            Value = 78
                        },
                        new
                        {
                            Id = new Guid("db3afc0c-c748-5011-b967-1f6d42e3908e"),
                            Name = "TF",
                            Value = 79
                        },
                        new
                        {
                            Id = new Guid("8393e1a5-7e1c-53d6-b0eb-ba1379877dbd"),
                            Name = "GA",
                            Value = 80
                        },
                        new
                        {
                            Id = new Guid("c49f6780-3761-5d92-a4ff-bf0b5e264254"),
                            Name = "GM",
                            Value = 81
                        },
                        new
                        {
                            Id = new Guid("4ed3d445-80c4-58a9-8f7e-83a033badf1a"),
                            Name = "GE",
                            Value = 82
                        },
                        new
                        {
                            Id = new Guid("036c3a18-12ca-5e25-8861-fd659013ff4c"),
                            Name = "DE",
                            Value = 83
                        },
                        new
                        {
                            Id = new Guid("5cf549d0-ed47-5bc5-a0f8-4d588713f305"),
                            Name = "GH",
                            Value = 84
                        },
                        new
                        {
                            Id = new Guid("d69f10e7-ad3e-5f9a-9e32-4ba9048bae37"),
                            Name = "GI",
                            Value = 85
                        },
                        new
                        {
                            Id = new Guid("e372028e-4411-5396-852d-f0f86c2668f0"),
                            Name = "GR",
                            Value = 86
                        },
                        new
                        {
                            Id = new Guid("c77555e1-b642-5cb5-9314-e2d0ec14cd04"),
                            Name = "GL",
                            Value = 87
                        },
                        new
                        {
                            Id = new Guid("c548c111-d3fe-53e1-9010-586ac478d9a3"),
                            Name = "GD",
                            Value = 88
                        },
                        new
                        {
                            Id = new Guid("90309b98-03a9-5741-ad21-48ac984f209b"),
                            Name = "GP",
                            Value = 89
                        },
                        new
                        {
                            Id = new Guid("562ac58e-c928-51a9-80d9-c35bfb31b3ec"),
                            Name = "GU",
                            Value = 90
                        },
                        new
                        {
                            Id = new Guid("e2f043a5-43b7-5615-be3f-e0362da2d863"),
                            Name = "GT",
                            Value = 91
                        },
                        new
                        {
                            Id = new Guid("fea57031-0299-5238-aa18-8541ee9e0db6"),
                            Name = "GG",
                            Value = 92
                        },
                        new
                        {
                            Id = new Guid("e6c8405d-7e72-5ac1-9894-7a78e8032df9"),
                            Name = "GN",
                            Value = 93
                        },
                        new
                        {
                            Id = new Guid("182166aa-eb3b-5e3d-ad3c-70bd64a8dd73"),
                            Name = "GW",
                            Value = 94
                        },
                        new
                        {
                            Id = new Guid("22a4eb55-6a17-5b9b-98b4-cc05ac38920c"),
                            Name = "GY",
                            Value = 95
                        },
                        new
                        {
                            Id = new Guid("131b50f1-3dcb-52a5-a5ff-602d0ff8678f"),
                            Name = "HT",
                            Value = 96
                        },
                        new
                        {
                            Id = new Guid("196e49a2-25f3-520c-a880-a4b5395e17ce"),
                            Name = "HM",
                            Value = 97
                        },
                        new
                        {
                            Id = new Guid("42eb797c-c869-5b8b-bad4-b369f2fa7a5f"),
                            Name = "VA",
                            Value = 98
                        },
                        new
                        {
                            Id = new Guid("a0494307-c04b-5ab8-81c8-68b251180cfe"),
                            Name = "HN",
                            Value = 99
                        },
                        new
                        {
                            Id = new Guid("8739795c-c974-583f-97e6-49f0bc6a1e49"),
                            Name = "HK",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("a890df0a-b817-5de7-bf1f-5514e2c56860"),
                            Name = "HU",
                            Value = 101
                        },
                        new
                        {
                            Id = new Guid("5191d108-a93c-5777-9fb5-94a494cdb119"),
                            Name = "IS",
                            Value = 102
                        },
                        new
                        {
                            Id = new Guid("7693b6ac-dc49-554b-adca-f95a064c0933"),
                            Name = "IN",
                            Value = 103
                        },
                        new
                        {
                            Id = new Guid("888bb708-ac4e-5400-9d18-0db5d6d06ded"),
                            Name = "ID",
                            Value = 104
                        },
                        new
                        {
                            Id = new Guid("cdbce150-be65-51cf-80ed-9b5349fb4d41"),
                            Name = "IR",
                            Value = 105
                        },
                        new
                        {
                            Id = new Guid("b85fef8a-c400-56fe-b639-6215281e8c21"),
                            Name = "IQ",
                            Value = 106
                        },
                        new
                        {
                            Id = new Guid("3f8129e5-c5a9-5cad-9944-5d7afb5d471c"),
                            Name = "IE",
                            Value = 107
                        },
                        new
                        {
                            Id = new Guid("a56761c9-8c85-5e7b-8654-cec9f34626db"),
                            Name = "IM",
                            Value = 108
                        },
                        new
                        {
                            Id = new Guid("22447866-e26e-53b1-85f1-fcd2b568251a"),
                            Name = "IL",
                            Value = 109
                        },
                        new
                        {
                            Id = new Guid("cda31d82-0dab-5cbc-a40d-fff89834f5a0"),
                            Name = "IT",
                            Value = 110
                        },
                        new
                        {
                            Id = new Guid("aaa97986-2ab2-5614-8d51-4fbe4b0bd28d"),
                            Name = "JM",
                            Value = 111
                        },
                        new
                        {
                            Id = new Guid("cdae5812-9605-5549-be21-25f7652ca3da"),
                            Name = "JP",
                            Value = 112
                        },
                        new
                        {
                            Id = new Guid("b61618b6-6328-58a4-94c3-75295bd00b81"),
                            Name = "JE",
                            Value = 113
                        },
                        new
                        {
                            Id = new Guid("ab8f1f6e-626b-57b0-8758-184d0b693736"),
                            Name = "JO",
                            Value = 114
                        },
                        new
                        {
                            Id = new Guid("911b4ca2-9437-5c03-9b52-2a78d8807631"),
                            Name = "KZ",
                            Value = 115
                        },
                        new
                        {
                            Id = new Guid("8a4638ce-3b6c-5ab7-854d-4728ebe66afb"),
                            Name = "KE",
                            Value = 116
                        },
                        new
                        {
                            Id = new Guid("24d2354f-4d51-53f2-8249-fb6441796051"),
                            Name = "KI",
                            Value = 117
                        },
                        new
                        {
                            Id = new Guid("fe870894-ad0b-53a6-bc8c-c7c802fa2f14"),
                            Name = "KP",
                            Value = 118
                        },
                        new
                        {
                            Id = new Guid("c36919ba-aa4b-5f10-908b-3c1bcc96705c"),
                            Name = "KR",
                            Value = 119
                        },
                        new
                        {
                            Id = new Guid("87d1ad1d-f77f-5b9e-9994-3d4ab7466c1c"),
                            Name = "KW",
                            Value = 120
                        },
                        new
                        {
                            Id = new Guid("db81bb2c-c516-5097-b4e5-c706b188fdbb"),
                            Name = "KG",
                            Value = 121
                        },
                        new
                        {
                            Id = new Guid("3db0274b-f881-59c1-ad96-84e72c31e66d"),
                            Name = "LA",
                            Value = 122
                        },
                        new
                        {
                            Id = new Guid("883d4ca8-e009-5ec1-9083-6ca1ac19023d"),
                            Name = "LV",
                            Value = 123
                        },
                        new
                        {
                            Id = new Guid("a5ad5137-7ded-568e-8a60-8cd490924e35"),
                            Name = "LB",
                            Value = 124
                        },
                        new
                        {
                            Id = new Guid("3bb7f983-1e58-57ec-80a2-2fee939174d4"),
                            Name = "LS",
                            Value = 125
                        },
                        new
                        {
                            Id = new Guid("60d78752-984c-5f4d-8c20-f912c9147e45"),
                            Name = "LR",
                            Value = 126
                        },
                        new
                        {
                            Id = new Guid("a0ac3524-93a3-5070-a0f7-0bb6582c5e45"),
                            Name = "LY",
                            Value = 127
                        },
                        new
                        {
                            Id = new Guid("5332780c-224a-52f6-aafb-f8763b6e4b08"),
                            Name = "LI",
                            Value = 128
                        },
                        new
                        {
                            Id = new Guid("15f1330e-f669-5b3b-a5b4-3f8d45511b08"),
                            Name = "LT",
                            Value = 129
                        },
                        new
                        {
                            Id = new Guid("185f6355-2b65-5d1a-a57a-fb58db09e075"),
                            Name = "LU",
                            Value = 130
                        },
                        new
                        {
                            Id = new Guid("bc957902-2843-5a76-8ff8-49062de963d5"),
                            Name = "MO",
                            Value = 131
                        },
                        new
                        {
                            Id = new Guid("2c2bd55f-77a1-51f6-945a-171f0833d8ab"),
                            Name = "MK",
                            Value = 132
                        },
                        new
                        {
                            Id = new Guid("c7efb0e1-55e4-51f0-b412-27d189779248"),
                            Name = "MG",
                            Value = 133
                        },
                        new
                        {
                            Id = new Guid("f1edb8d6-47d2-5c44-a87a-ad6a1182f322"),
                            Name = "MW",
                            Value = 134
                        },
                        new
                        {
                            Id = new Guid("384ce04f-9efe-535b-a287-cf4b51ae4feb"),
                            Name = "MY",
                            Value = 135
                        },
                        new
                        {
                            Id = new Guid("b4da38f4-9c0c-5170-a72a-1e55a9ca7c3e"),
                            Name = "MV",
                            Value = 136
                        },
                        new
                        {
                            Id = new Guid("1762bd94-78b2-5f16-b9fb-dd8982b9c17d"),
                            Name = "ML",
                            Value = 137
                        },
                        new
                        {
                            Id = new Guid("661456fa-9d44-5392-8f68-f11a940eb490"),
                            Name = "MT",
                            Value = 138
                        },
                        new
                        {
                            Id = new Guid("aadf8b61-48c0-5f25-8cac-e0c00560610b"),
                            Name = "MH",
                            Value = 139
                        },
                        new
                        {
                            Id = new Guid("15e7e7ec-d92d-5e9b-a477-846342e11d90"),
                            Name = "MQ",
                            Value = 140
                        },
                        new
                        {
                            Id = new Guid("ac6b8c2a-9b50-5f9a-af3e-5981d7b64b1a"),
                            Name = "MR",
                            Value = 141
                        },
                        new
                        {
                            Id = new Guid("7e3053fc-ee6a-56ca-997f-0e573d253a98"),
                            Name = "MU",
                            Value = 142
                        },
                        new
                        {
                            Id = new Guid("60a3df99-e7ca-5733-883d-4399a5756f06"),
                            Name = "YT",
                            Value = 143
                        },
                        new
                        {
                            Id = new Guid("db9f898b-6c14-5f03-99b6-fc575998f642"),
                            Name = "MX",
                            Value = 144
                        },
                        new
                        {
                            Id = new Guid("dcf777dd-3f8e-564f-ab53-61be1e636f63"),
                            Name = "FM",
                            Value = 145
                        },
                        new
                        {
                            Id = new Guid("434f3f5e-4b8f-558c-90f2-3cf067d2966b"),
                            Name = "MD",
                            Value = 146
                        },
                        new
                        {
                            Id = new Guid("7b02f7ab-d7e0-50f1-8a0e-d01aee2985ed"),
                            Name = "MC",
                            Value = 147
                        },
                        new
                        {
                            Id = new Guid("3062c64f-55e5-5d4a-b3ce-9f6d2fea12ad"),
                            Name = "MN",
                            Value = 148
                        },
                        new
                        {
                            Id = new Guid("da211c10-84d0-5b10-8a42-21df72ace911"),
                            Name = "ME",
                            Value = 149
                        },
                        new
                        {
                            Id = new Guid("800094bf-09a5-5e57-acdb-4b0ef07410e6"),
                            Name = "MS",
                            Value = 150
                        },
                        new
                        {
                            Id = new Guid("3fa079f8-d815-5d56-a641-a8916769b379"),
                            Name = "MA",
                            Value = 151
                        },
                        new
                        {
                            Id = new Guid("8c8a0911-0209-58d3-b3b2-2507f6cce15e"),
                            Name = "MZ",
                            Value = 152
                        },
                        new
                        {
                            Id = new Guid("06c60097-ddb7-5e86-ae5a-f490899bf4f5"),
                            Name = "MM",
                            Value = 153
                        },
                        new
                        {
                            Id = new Guid("f6e0e6f9-3e42-59b4-935e-68c7580c1aa5"),
                            Name = "NA",
                            Value = 154
                        },
                        new
                        {
                            Id = new Guid("798cc2f8-b152-54ec-b19a-4cecccc1df4e"),
                            Name = "NR",
                            Value = 155
                        },
                        new
                        {
                            Id = new Guid("ddd0fa3b-f99f-52db-b344-24cdd673c4f1"),
                            Name = "NP",
                            Value = 156
                        },
                        new
                        {
                            Id = new Guid("63fa6c9d-0816-58a1-8353-f795c86d9d56"),
                            Name = "NL",
                            Value = 157
                        },
                        new
                        {
                            Id = new Guid("0fa10dcc-15f8-5bcc-88b9-f6265cb50bb0"),
                            Name = "NC",
                            Value = 158
                        },
                        new
                        {
                            Id = new Guid("0b863bbd-aeec-579a-87a5-2f201e76fe4a"),
                            Name = "NZ",
                            Value = 159
                        },
                        new
                        {
                            Id = new Guid("a1a41f56-47aa-54b1-af63-bf1c063557a7"),
                            Name = "NI",
                            Value = 160
                        },
                        new
                        {
                            Id = new Guid("2da8c60a-3d6b-5515-a35a-ebeb8c90e358"),
                            Name = "NE",
                            Value = 161
                        },
                        new
                        {
                            Id = new Guid("4460925e-4d98-5309-9f69-9648e42f4e43"),
                            Name = "NG",
                            Value = 162
                        },
                        new
                        {
                            Id = new Guid("8842c6c9-ac68-52ec-8246-17afcf5ee173"),
                            Name = "NU",
                            Value = 163
                        },
                        new
                        {
                            Id = new Guid("9285a80f-7f82-5d48-b337-1d8738b9742a"),
                            Name = "NF",
                            Value = 164
                        },
                        new
                        {
                            Id = new Guid("0491921e-2a93-50cc-889f-24dbdf9aff7e"),
                            Name = "MP",
                            Value = 165
                        },
                        new
                        {
                            Id = new Guid("6f485592-43af-51fb-9884-3972f3629dac"),
                            Name = "NO",
                            Value = 166
                        },
                        new
                        {
                            Id = new Guid("55cdd703-6cf1-52f7-92eb-70ada9c894a3"),
                            Name = "OM",
                            Value = 167
                        },
                        new
                        {
                            Id = new Guid("e874406a-c436-5b9d-a1f4-2b2a7b3c6c8b"),
                            Name = "PK",
                            Value = 168
                        },
                        new
                        {
                            Id = new Guid("0ea16bb1-6dea-54bc-90ef-e910469fd766"),
                            Name = "PW",
                            Value = 169
                        },
                        new
                        {
                            Id = new Guid("5bf6cf35-7c7f-5435-aeea-ee0c6f15789d"),
                            Name = "PS",
                            Value = 170
                        },
                        new
                        {
                            Id = new Guid("28ab882b-6f9a-58df-b71f-cd17253aef58"),
                            Name = "PA",
                            Value = 171
                        },
                        new
                        {
                            Id = new Guid("833f29d7-c624-54b5-a288-3aae5ab9bb4d"),
                            Name = "PG",
                            Value = 172
                        },
                        new
                        {
                            Id = new Guid("cfa74244-5e5b-52a1-86c3-8b7070b48d62"),
                            Name = "PY",
                            Value = 173
                        },
                        new
                        {
                            Id = new Guid("015e6cf5-99a2-5bff-80a4-da65cdb2504c"),
                            Name = "PE",
                            Value = 174
                        },
                        new
                        {
                            Id = new Guid("dc7e53c5-b39a-5f7d-840e-1295678ce63e"),
                            Name = "PH",
                            Value = 175
                        },
                        new
                        {
                            Id = new Guid("bff34991-46c3-58db-b615-98d3fce5d838"),
                            Name = "PN",
                            Value = 176
                        },
                        new
                        {
                            Id = new Guid("9c63d493-5c1c-5355-a7c7-6638b5eb5cf1"),
                            Name = "PL",
                            Value = 177
                        },
                        new
                        {
                            Id = new Guid("78be49a2-655c-5b7f-8e3f-a9212288f841"),
                            Name = "PT",
                            Value = 178
                        },
                        new
                        {
                            Id = new Guid("116cf350-4e34-562a-a41d-89c192fe4cee"),
                            Name = "PR",
                            Value = 179
                        },
                        new
                        {
                            Id = new Guid("37a830fd-7183-5d4a-bd43-9e863133b956"),
                            Name = "QA",
                            Value = 180
                        },
                        new
                        {
                            Id = new Guid("b270df57-7c93-520f-9021-eb1dc53cf2a5"),
                            Name = "RE",
                            Value = 181
                        },
                        new
                        {
                            Id = new Guid("59d3d920-8728-5e15-b935-db0d7ade9dcf"),
                            Name = "RO",
                            Value = 182
                        },
                        new
                        {
                            Id = new Guid("673f7f97-a929-56f3-9cae-67b561942322"),
                            Name = "RU",
                            Value = 183
                        },
                        new
                        {
                            Id = new Guid("637f71cb-f027-5a12-b2bc-b61e508fb22e"),
                            Name = "RW",
                            Value = 184
                        },
                        new
                        {
                            Id = new Guid("9d350de7-2ba4-58ae-b464-ca51989d81bc"),
                            Name = "BL",
                            Value = 185
                        },
                        new
                        {
                            Id = new Guid("fcc0c895-2c05-562e-bde9-48b7c3dca80b"),
                            Name = "SH",
                            Value = 186
                        },
                        new
                        {
                            Id = new Guid("901277d6-57a3-5da3-8fb3-5991a72bcfcf"),
                            Name = "KN",
                            Value = 187
                        },
                        new
                        {
                            Id = new Guid("ef01e439-26cd-5714-93e3-e995e76ceb0f"),
                            Name = "LC",
                            Value = 188
                        },
                        new
                        {
                            Id = new Guid("b0364f0f-993d-5520-986b-d4c7f3ff4355"),
                            Name = "MF",
                            Value = 189
                        },
                        new
                        {
                            Id = new Guid("67af16fa-15bc-558e-99d2-539247de42f8"),
                            Name = "PM",
                            Value = 190
                        },
                        new
                        {
                            Id = new Guid("0d32f844-6b51-51b7-a340-9c451f4477dd"),
                            Name = "VC",
                            Value = 191
                        },
                        new
                        {
                            Id = new Guid("394817a0-d725-5f8e-9e89-92c8c32e8063"),
                            Name = "WS",
                            Value = 192
                        },
                        new
                        {
                            Id = new Guid("9fe8aa5c-534d-5a3a-aada-17ee7228acac"),
                            Name = "SM",
                            Value = 193
                        },
                        new
                        {
                            Id = new Guid("282293c3-838e-5e7c-b7f3-fd9a090d7a82"),
                            Name = "ST",
                            Value = 194
                        },
                        new
                        {
                            Id = new Guid("cf297a21-2855-59af-ac2e-78fc6f5de4f0"),
                            Name = "SA",
                            Value = 195
                        },
                        new
                        {
                            Id = new Guid("2ebd8c51-03ee-51ce-aaf5-a8c2e807ea81"),
                            Name = "SN",
                            Value = 196
                        },
                        new
                        {
                            Id = new Guid("ea6b5c91-d6c2-5610-9725-14bb0e398d78"),
                            Name = "RS",
                            Value = 197
                        },
                        new
                        {
                            Id = new Guid("6c461ee5-3045-5379-a186-c368d1b370d5"),
                            Name = "SC",
                            Value = 198
                        },
                        new
                        {
                            Id = new Guid("ee3b1b58-fe6b-50c4-990b-7fd32b0e423c"),
                            Name = "SL",
                            Value = 199
                        },
                        new
                        {
                            Id = new Guid("7501cc1e-1f98-532c-bfe1-025d0fc51a0a"),
                            Name = "SG",
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("dbda2871-52ec-51e8-9f86-ff2168280767"),
                            Name = "SX",
                            Value = 201
                        },
                        new
                        {
                            Id = new Guid("95c517f2-17cf-535f-ad2b-aedfe8618a93"),
                            Name = "SK",
                            Value = 202
                        },
                        new
                        {
                            Id = new Guid("f858606b-6ef4-5be0-b9fb-c0c2aab7cc55"),
                            Name = "SI",
                            Value = 203
                        },
                        new
                        {
                            Id = new Guid("7028d960-87ab-55b4-b841-42a0fde078d2"),
                            Name = "SB",
                            Value = 204
                        },
                        new
                        {
                            Id = new Guid("93cf88c6-1f8c-57dc-96f7-09119cfef9ea"),
                            Name = "SO",
                            Value = 205
                        },
                        new
                        {
                            Id = new Guid("9d577108-a988-5c11-aff3-f9e79b5b1f26"),
                            Name = "ZA",
                            Value = 206
                        },
                        new
                        {
                            Id = new Guid("fdecc802-7af2-5100-8475-9cfa91a9922c"),
                            Name = "GS",
                            Value = 207
                        },
                        new
                        {
                            Id = new Guid("7220d84a-ac50-5622-a9d4-dff6e43f9365"),
                            Name = "SS",
                            Value = 208
                        },
                        new
                        {
                            Id = new Guid("10ef81c2-b9bd-5648-85e3-0db8d03b0ea0"),
                            Name = "ES",
                            Value = 209
                        },
                        new
                        {
                            Id = new Guid("efcc8be9-286c-5ad0-8f8d-2496de3bd512"),
                            Name = "LK",
                            Value = 210
                        },
                        new
                        {
                            Id = new Guid("07098226-aee3-5dd7-8dbe-3b2386a12219"),
                            Name = "SD",
                            Value = 211
                        },
                        new
                        {
                            Id = new Guid("a4358603-8b4f-50e4-810b-3a038847e6d6"),
                            Name = "SR",
                            Value = 212
                        },
                        new
                        {
                            Id = new Guid("5ef0dcc4-ed64-58ed-9201-e93dbb8f8e71"),
                            Name = "SJ",
                            Value = 213
                        },
                        new
                        {
                            Id = new Guid("edda6af9-6ea0-5f8c-bfc7-04bc97769414"),
                            Name = "SZ",
                            Value = 214
                        },
                        new
                        {
                            Id = new Guid("674dd772-6c16-5778-9ca7-50591bfa0391"),
                            Name = "SE",
                            Value = 215
                        },
                        new
                        {
                            Id = new Guid("ce810cdb-5ebd-5f54-a622-95fffa5e2bb9"),
                            Name = "CH",
                            Value = 216
                        },
                        new
                        {
                            Id = new Guid("e304fdd1-9cdd-52f9-b086-10b941fff6be"),
                            Name = "SY",
                            Value = 217
                        },
                        new
                        {
                            Id = new Guid("cf424494-8cfc-54b4-a946-5e80476fd470"),
                            Name = "TW",
                            Value = 218
                        },
                        new
                        {
                            Id = new Guid("100abe89-3738-5c4b-bec0-3eb0fd9a8e64"),
                            Name = "TJ",
                            Value = 219
                        },
                        new
                        {
                            Id = new Guid("8f3016bf-c223-5021-8c47-eb83b0c3b066"),
                            Name = "TZ",
                            Value = 220
                        },
                        new
                        {
                            Id = new Guid("bdcc6531-b1a9-50da-846b-a5ac38638aa7"),
                            Name = "TH",
                            Value = 221
                        },
                        new
                        {
                            Id = new Guid("b7e287da-6634-5e60-a69d-f4522e8bb60f"),
                            Name = "TL",
                            Value = 222
                        },
                        new
                        {
                            Id = new Guid("f2e93d2f-c62c-536e-ae96-aeeb708c839a"),
                            Name = "TG",
                            Value = 223
                        },
                        new
                        {
                            Id = new Guid("c280633f-9986-5653-a17a-a055da26317d"),
                            Name = "TK",
                            Value = 224
                        },
                        new
                        {
                            Id = new Guid("ca9621b1-8a10-518b-ac5c-7c7186a43c48"),
                            Name = "TO",
                            Value = 225
                        },
                        new
                        {
                            Id = new Guid("8d9fb7d1-6e60-5824-8f05-a95796beb66b"),
                            Name = "TT",
                            Value = 226
                        },
                        new
                        {
                            Id = new Guid("18348345-8002-5d20-a546-0b9b6c322245"),
                            Name = "TN",
                            Value = 227
                        },
                        new
                        {
                            Id = new Guid("dfcf4748-3629-5c97-b9a5-6002d425c8cd"),
                            Name = "TR",
                            Value = 228
                        },
                        new
                        {
                            Id = new Guid("7e5cdb60-3a68-51fd-bdea-8b44de844b91"),
                            Name = "TM",
                            Value = 229
                        },
                        new
                        {
                            Id = new Guid("43eaaaa4-0695-5c0b-9351-fc57479aa679"),
                            Name = "TC",
                            Value = 230
                        },
                        new
                        {
                            Id = new Guid("790cf85b-553f-5427-a6be-ee9e42cbe3cc"),
                            Name = "TV",
                            Value = 231
                        },
                        new
                        {
                            Id = new Guid("ebd9e2a1-6e12-5f3e-8a1c-b6c278987a30"),
                            Name = "UG",
                            Value = 232
                        },
                        new
                        {
                            Id = new Guid("21e05bce-f28c-52ce-b357-c09d3c947048"),
                            Name = "UA",
                            Value = 233
                        },
                        new
                        {
                            Id = new Guid("41e6b339-7f13-5932-9d8b-e0589a72bb91"),
                            Name = "AE",
                            Value = 234
                        },
                        new
                        {
                            Id = new Guid("acc996c9-9a2a-5bff-9e92-379e811de520"),
                            Name = "GB",
                            Value = 235
                        },
                        new
                        {
                            Id = new Guid("509ae36d-603d-56b6-8180-f4be7a63d858"),
                            Name = "US",
                            Value = 236
                        },
                        new
                        {
                            Id = new Guid("45d55f9a-6a07-5f9d-83f1-0ec4fa5722e5"),
                            Name = "UM",
                            Value = 237
                        },
                        new
                        {
                            Id = new Guid("7e1d867f-a909-5ea0-ba3a-882b2344ec87"),
                            Name = "UY",
                            Value = 238
                        },
                        new
                        {
                            Id = new Guid("0b421075-8e50-5bfd-82bf-06b8bb9ab30d"),
                            Name = "UZ",
                            Value = 239
                        },
                        new
                        {
                            Id = new Guid("259d51c1-aee0-5216-8c96-a2f46ee835bb"),
                            Name = "VU",
                            Value = 240
                        },
                        new
                        {
                            Id = new Guid("9ac661eb-0c14-55b6-bca7-41de9f9e0edb"),
                            Name = "VE",
                            Value = 241
                        },
                        new
                        {
                            Id = new Guid("980369ae-b3e8-5a08-9bd2-d0cdecbe1b7e"),
                            Name = "VN",
                            Value = 242
                        },
                        new
                        {
                            Id = new Guid("87fbaca6-cdd5-5864-af75-3d4e001a004d"),
                            Name = "VG",
                            Value = 243
                        },
                        new
                        {
                            Id = new Guid("f3c5709a-b6e1-5ca6-9da0-1fdc05e76e53"),
                            Name = "VI",
                            Value = 244
                        },
                        new
                        {
                            Id = new Guid("fd0ffbff-5d9f-5e0d-80d8-1b9e3a2a8e56"),
                            Name = "WF",
                            Value = 245
                        },
                        new
                        {
                            Id = new Guid("0b671452-07a8-5dbc-9a6c-d9f10ab37671"),
                            Name = "EH",
                            Value = 246
                        },
                        new
                        {
                            Id = new Guid("017ef99f-d2fe-519c-b49a-b72b4d34b955"),
                            Name = "YE",
                            Value = 247
                        },
                        new
                        {
                            Id = new Guid("0b2c0726-6334-5eb3-aa3c-f199c7d27254"),
                            Name = "ZM",
                            Value = 248
                        },
                        new
                        {
                            Id = new Guid("9a92c6a3-eb9c-5806-b598-b5b706727fd2"),
                            Name = "ZW",
                            Value = 249
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MachineDimensionsType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9c9ce6b-e387-506a-aa11-e94d4e5e96e8"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("69521354-580d-5690-8323-293c1bf9a250"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("f175c73a-7821-5416-b4d9-a6a442d86675"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MillingMachineTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8ab862c-c24f-5a4d-aecf-46f94ec58cfb"),
                            Name = "TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("08341e4f-2a5f-519a-a766-a2d6c6dc22c0"),
                            Name = "TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("d8e0cec5-ff22-5fe3-b631-7d02ddfa74d8"),
                            Name = "TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("3ebb0273-3ca0-5b1d-a1f0-ee6de2883ada"),
                            Name = "TYPE_4",
                            Value = 3
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("OtherTechnologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0543c433-b71c-5dec-885a-6346bfb0136a"),
                            Name = "DeepHoleDrilling",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("5dec8698-7fc3-5db7-8465-13339f912b69"),
                            Name = "ThreadsM",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("b9837b14-b9b1-5ea3-8999-ef92a59f6243"),
                            Name = "ThreadsTr",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("c677f037-7e6d-59eb-b928-bb3fdb5c00b0"),
                            Name = "Toothings",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("eef999c2-d4b8-5c34-b6c5-a581bdbfc25f"),
                            Name = "Engravings",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("38346732-5a23-59dd-b988-adbd88b4bb24"),
                            Name = "LaserMarking",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("734cdf67-1834-510c-bb46-cf4c9384207b"),
                            Name = "Knurling",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("110b356b-aff5-58a0-a989-418aec685097"),
                            Name = "Annealing",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("767ff03f-cdd8-520b-a452-920045c12ca1"),
                            Name = "Other",
                            Value = 8
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("MillingMachineDimensionsTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MillingMachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MillingMachineDimensionsTypeId");

                    b.HasIndex("MillingMachineTypeId");

                    b.ToTable("MillingMachine");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MillingMachineDimensionsTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38a3299e-44ab-5ff9-85fc-7f73ea5bca3e"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("f777012c-fab2-5efd-ab35-9a28a0bd3575"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("c437bb5d-d409-5326-80d8-c8f878f39910"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TurningMachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TurningMachineTypeId");

                    b.ToTable("TurningMachines");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.TurningMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("TurningMachineTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c0ec856-54c2-5235-a2a3-23fd2053489e"),
                            Name = "TURNING_MACHINE_TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("4d4834c2-a801-5d73-89b4-a8674e26617c"),
                            Name = "TURNING_MACHINE_TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("a212118c-3b4d-5575-9095-0e9cf5d65e29"),
                            Name = "TURNING_MACHINE_TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("13521bfe-f43f-5e74-aac6-8e228552d603"),
                            Name = "TURNING_MACHINE_TYPE_4",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("0002a08a-4ad1-5ec8-b356-0bb4143266fe"),
                            Name = "TURNING_MACHINE_TYPE_5",
                            Value = 4
                        });
                });

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", null)
                        .WithMany()
                        .HasForeignKey("OtherTechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", "AddressType")
                        .WithMany()
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCodeType", "CountryCodeType")
                        .WithMany()
                        .HasForeignKey("CountryCodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressType");

                    b.Navigation("CountryCodeType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySizeType", "CompanySizeType")
                        .WithMany()
                        .HasForeignKey("CompanySizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySizeType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithOne("CustomerAdditionalInfo")
                        .HasForeignKey("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("MillingMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", "MillingMachineDimensionsType")
                        .WithMany()
                        .HasForeignKey("MillingMachineDimensionsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", "MillingMachineType")
                        .WithMany()
                        .HasForeignKey("MillingMachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MillingMachineDimensionsType");

                    b.Navigation("MillingMachineType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Registration", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithOne("Registration")
                        .HasForeignKey("Oroox.SubSuppliers.Domain.Entities.Registration", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("TurningMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.TurningMachineType", "TurningMachineType")
                        .WithMany()
                        .HasForeignKey("TurningMachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TurningMachineType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerAdditionalInfo");

                    b.Navigation("MillingMachines");

                    b.Navigation("Registration");

                    b.Navigation("TurningMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
