// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oroox.SubSuppliers.Domain.Context;

namespace Oroox.SubSuppliers.Domain.Migrations
{
    [DbContext(typeof(SubSuppliersContext))]
    [Migration("20210521133104_AddCustomer")]
    partial class AddCustomer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.Property<Guid>("CertificationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CertificationsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("CertificationCustomer");
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OtherTechnologiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomersId", "OtherTechnologiesId");

                    b.HasIndex("OtherTechnologiesId");

                    b.ToTable("CustomerOtherTechnology");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Certifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2a4d5e1-ada4-442c-9029-0291f19da8f9"),
                            Name = "ISO9001",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("5e750f90-ba52-4d08-a459-760176649bb5"),
                            Name = "ISO14001",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("2f0bf6b9-56ef-4e71-8e44-ee795e0b31f7"),
                            Name = "ISO13485",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("3b10c3fb-1a5a-4164-a442-42eeac6cf7bb"),
                            Name = "ITAF16949",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("e6ad54ae-0a96-4c11-bd26-e4b353de61af"),
                            Name = "EN9100",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("2160d49c-5cc6-43b0-9c74-6d916640c0d9"),
                            Name = "Other",
                            Value = 5
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.ContactPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContactPerson");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("AddressTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryCodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("CountryCodeTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanySizeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerAdditionalInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanySizeTypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageAndFastestLeadTimeMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageAndFastestLeadTimeTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageWorkingHoursPerWeek")
                        .HasColumnType("float");

                    b.Property<bool?>("CanUseStepFiles")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialCharacteristics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTolerances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkingShiftsPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerAdditionalInfo");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("AddressTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67272ee9-40f2-472e-ba74-6c7ab12ad37d"),
                            Name = "Shipping",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("1a690b08-1f0a-4ae0-9282-b229e3ba336c"),
                            Name = "Billing",
                            Value = 1
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySizeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("CompanySizeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21460743-e733-4146-8e3a-e57fe0db1ac9"),
                            Name = "LessThan10",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("e2035d07-c048-4fd8-ba7d-de4b338a3909"),
                            Name = "LessThan25",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("5d1c6790-ce59-4315-b8cc-4d928de65e3e"),
                            Name = "LessThan50",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("8d391ae5-462e-4593-9817-c4aaad5f2418"),
                            Name = "LessThan100",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("297e5990-5e7b-4dd5-8840-5b2ebc735414"),
                            Name = "MoreThan100",
                            Value = 101
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("CountryCodeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ee02752a-175b-4f4d-9a6a-9cdbb1cabb1f"),
                            Name = "AF",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("de1eba2a-8bfa-4655-b600-6dedb4360faa"),
                            Name = "AX",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("f547c091-3ad0-4c23-9ddd-f0dd1f21c9c8"),
                            Name = "AL",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("9170884d-0805-4cc6-8bd6-9e91679cf12f"),
                            Name = "DZ",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("58fe6adb-ce0f-4b0a-a60f-446cfef69844"),
                            Name = "AS",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("d061ca3d-190b-469b-a7d9-065159bd2555"),
                            Name = "AD",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("6a77f82b-1150-42d1-bc85-25ded591c345"),
                            Name = "AO",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("fcee1adb-3dc9-4cea-bda8-a61cc0b0f9a2"),
                            Name = "AI",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("0048c727-0274-4436-975e-5193969fd82e"),
                            Name = "AQ",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("f7bbb2e9-1676-4a94-8c10-fce561c4cab6"),
                            Name = "AG",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("698e1841-1bfb-42c6-890d-6dd99d6d3256"),
                            Name = "AR",
                            Value = 11
                        },
                        new
                        {
                            Id = new Guid("7b33fa09-354f-459c-8fb8-6f66b0ab05d2"),
                            Name = "AM",
                            Value = 12
                        },
                        new
                        {
                            Id = new Guid("2a08f668-cbad-4dd0-a2eb-85aad266ab7a"),
                            Name = "AW",
                            Value = 13
                        },
                        new
                        {
                            Id = new Guid("877636f9-1976-4908-8e07-0afdb7cd27f9"),
                            Name = "AU",
                            Value = 14
                        },
                        new
                        {
                            Id = new Guid("a28c5acc-dfb4-4ce3-aec2-eefc6119a5fe"),
                            Name = "AT",
                            Value = 15
                        },
                        new
                        {
                            Id = new Guid("26acbeef-277e-479c-b6ad-238b40c0cbff"),
                            Name = "AZ",
                            Value = 16
                        },
                        new
                        {
                            Id = new Guid("ac69545f-c506-4c0e-b344-ac35b044da55"),
                            Name = "BS",
                            Value = 17
                        },
                        new
                        {
                            Id = new Guid("699bd98f-58f4-4361-b157-c02205865e24"),
                            Name = "BH",
                            Value = 18
                        },
                        new
                        {
                            Id = new Guid("6d4ab862-fead-49e7-a12c-aa6f923350af"),
                            Name = "BD",
                            Value = 19
                        },
                        new
                        {
                            Id = new Guid("389fb376-963d-45f2-82ad-35ee2ca35374"),
                            Name = "BB",
                            Value = 20
                        },
                        new
                        {
                            Id = new Guid("a9688286-50dc-4263-8796-1b51cd99d985"),
                            Name = "BY",
                            Value = 21
                        },
                        new
                        {
                            Id = new Guid("7df8285d-920a-4205-af29-a06f801e35d3"),
                            Name = "BE",
                            Value = 22
                        },
                        new
                        {
                            Id = new Guid("ad8ff767-9c3b-46ff-b72b-b5ae481f4aca"),
                            Name = "BZ",
                            Value = 23
                        },
                        new
                        {
                            Id = new Guid("acdefcb0-e8cd-4130-9b9c-c5635b326e5b"),
                            Name = "BJ",
                            Value = 24
                        },
                        new
                        {
                            Id = new Guid("b1faf8d7-37a0-487c-8b31-de1273291f6b"),
                            Name = "BM",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("7bf59fc7-ea57-4e9c-a11e-f217767c5980"),
                            Name = "BT",
                            Value = 26
                        },
                        new
                        {
                            Id = new Guid("84ca8e0b-0a50-4fec-8b64-25cd73ffb08d"),
                            Name = "BO",
                            Value = 27
                        },
                        new
                        {
                            Id = new Guid("3cd59006-2cc2-473b-bc62-478ef49d7de3"),
                            Name = "BQ",
                            Value = 28
                        },
                        new
                        {
                            Id = new Guid("e6a99909-5759-48b1-91d2-efffeabe3a11"),
                            Name = "BA",
                            Value = 29
                        },
                        new
                        {
                            Id = new Guid("b1009f00-aa17-449b-8dba-36b113ea9aa9"),
                            Name = "BW",
                            Value = 30
                        },
                        new
                        {
                            Id = new Guid("322f8a25-79cb-4784-b225-6d232caeeb71"),
                            Name = "BV",
                            Value = 31
                        },
                        new
                        {
                            Id = new Guid("f60c0eb7-a830-4390-a80b-d2e73f82fb64"),
                            Name = "BR",
                            Value = 32
                        },
                        new
                        {
                            Id = new Guid("bc4d43fb-b046-42ab-85f8-61efe7b70536"),
                            Name = "IO",
                            Value = 33
                        },
                        new
                        {
                            Id = new Guid("58742590-9402-4b92-882e-d83fc725482d"),
                            Name = "BN",
                            Value = 34
                        },
                        new
                        {
                            Id = new Guid("dc193b6f-18b6-4bbc-a472-8a9b57b2f3f2"),
                            Name = "BG",
                            Value = 35
                        },
                        new
                        {
                            Id = new Guid("392599b3-a796-47fa-895a-c2cac03501ba"),
                            Name = "BF",
                            Value = 36
                        },
                        new
                        {
                            Id = new Guid("1d94f49f-1b86-4030-8d76-050649351da5"),
                            Name = "BI",
                            Value = 37
                        },
                        new
                        {
                            Id = new Guid("6cc4d49f-966f-422c-8219-ed6a2672c4f7"),
                            Name = "CV",
                            Value = 38
                        },
                        new
                        {
                            Id = new Guid("e19c21fb-13b7-4843-87b1-a74aa064f8c9"),
                            Name = "KH",
                            Value = 39
                        },
                        new
                        {
                            Id = new Guid("76f3ab8a-771d-4fe6-a227-c14f92b04d60"),
                            Name = "CM",
                            Value = 40
                        },
                        new
                        {
                            Id = new Guid("51bea4f6-0a29-4d5d-9b83-3043080ed789"),
                            Name = "CA",
                            Value = 41
                        },
                        new
                        {
                            Id = new Guid("72050860-67c4-4eb0-add5-c3618ea6d543"),
                            Name = "KY",
                            Value = 42
                        },
                        new
                        {
                            Id = new Guid("b5a56e19-479d-40b3-b801-1247679cc13b"),
                            Name = "CF",
                            Value = 43
                        },
                        new
                        {
                            Id = new Guid("634df984-ab06-463d-be69-691f5d4c566b"),
                            Name = "TD",
                            Value = 44
                        },
                        new
                        {
                            Id = new Guid("133479e1-311e-4b1c-8bae-a2f216577737"),
                            Name = "CL",
                            Value = 45
                        },
                        new
                        {
                            Id = new Guid("4b905fe7-3ffc-4033-aa2a-0863b9c92523"),
                            Name = "CN",
                            Value = 46
                        },
                        new
                        {
                            Id = new Guid("84adffcc-ea28-4d36-a5ca-6f2677843910"),
                            Name = "CX",
                            Value = 47
                        },
                        new
                        {
                            Id = new Guid("66e934ae-9eaf-4a52-a1ef-be963a9297c2"),
                            Name = "CC",
                            Value = 48
                        },
                        new
                        {
                            Id = new Guid("197d16b2-94a1-4cb3-94de-28614c817a72"),
                            Name = "CO",
                            Value = 49
                        },
                        new
                        {
                            Id = new Guid("56758042-868b-4c65-9c80-ae751dcf8825"),
                            Name = "KM",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("3fc99b18-c72b-4e88-9baf-ff43d3228e97"),
                            Name = "CG",
                            Value = 51
                        },
                        new
                        {
                            Id = new Guid("c9a2f1dd-4136-49db-80f1-be6e1a226d74"),
                            Name = "CD",
                            Value = 52
                        },
                        new
                        {
                            Id = new Guid("46f48d7c-8f16-44eb-a48b-5132ed9d1e77"),
                            Name = "CK",
                            Value = 53
                        },
                        new
                        {
                            Id = new Guid("b35bde70-3404-44f3-9a5e-a15b5b41847d"),
                            Name = "CR",
                            Value = 54
                        },
                        new
                        {
                            Id = new Guid("47a25aa3-d2b2-4ab1-8aef-cdd6edcee10e"),
                            Name = "CI",
                            Value = 55
                        },
                        new
                        {
                            Id = new Guid("0369a7a1-3693-4c77-be39-fb206f9f0a4a"),
                            Name = "HR",
                            Value = 56
                        },
                        new
                        {
                            Id = new Guid("153f28f3-0836-4664-962e-ae8aeeaf3103"),
                            Name = "CU",
                            Value = 57
                        },
                        new
                        {
                            Id = new Guid("1828affa-607e-4cee-8bed-dd15d80a3ddb"),
                            Name = "CW",
                            Value = 58
                        },
                        new
                        {
                            Id = new Guid("35cf161c-5de5-4cb1-a668-810064dfa37a"),
                            Name = "CY",
                            Value = 59
                        },
                        new
                        {
                            Id = new Guid("74dc9baf-3b2a-411f-8d9d-c758a54b220e"),
                            Name = "CZ",
                            Value = 60
                        },
                        new
                        {
                            Id = new Guid("c963fb17-caab-4446-9324-98f0abc5fda4"),
                            Name = "DK",
                            Value = 61
                        },
                        new
                        {
                            Id = new Guid("ce70d9f3-0cd7-47ea-b449-321d2b47d5ba"),
                            Name = "DJ",
                            Value = 62
                        },
                        new
                        {
                            Id = new Guid("9d1feccd-b34e-43ac-a1f9-37ed65767ec6"),
                            Name = "DM",
                            Value = 63
                        },
                        new
                        {
                            Id = new Guid("72faf281-3a64-470d-9c4f-cba7745f0c3d"),
                            Name = "DO",
                            Value = 64
                        },
                        new
                        {
                            Id = new Guid("3159abab-bb7e-445e-aef6-aff79ee87458"),
                            Name = "EC",
                            Value = 65
                        },
                        new
                        {
                            Id = new Guid("f02cd36c-3499-47ce-b732-b87ce3eb9772"),
                            Name = "EG",
                            Value = 66
                        },
                        new
                        {
                            Id = new Guid("037afd35-f200-4e0b-8ba4-52612c136063"),
                            Name = "SV",
                            Value = 67
                        },
                        new
                        {
                            Id = new Guid("aca4ad52-09ea-43f6-9507-ff50a4f8183f"),
                            Name = "GQ",
                            Value = 68
                        },
                        new
                        {
                            Id = new Guid("1a3acd53-90b4-49e8-9d01-2afea273ee0e"),
                            Name = "ER",
                            Value = 69
                        },
                        new
                        {
                            Id = new Guid("fc4d9cd2-5af0-4636-bd48-5298636049d3"),
                            Name = "EE",
                            Value = 70
                        },
                        new
                        {
                            Id = new Guid("14a79347-9a83-4715-a2a1-1906f071d3a8"),
                            Name = "ET",
                            Value = 71
                        },
                        new
                        {
                            Id = new Guid("6c8c9ed6-2b2b-4a22-a154-e5e7c34cd6e2"),
                            Name = "FK",
                            Value = 72
                        },
                        new
                        {
                            Id = new Guid("77b58ec3-4d73-40d4-ab2a-f7aaad42c443"),
                            Name = "FO",
                            Value = 73
                        },
                        new
                        {
                            Id = new Guid("202eb601-d2c4-43e6-b441-754e989f9bda"),
                            Name = "FJ",
                            Value = 74
                        },
                        new
                        {
                            Id = new Guid("b254c038-3ab8-4b0a-abd7-4a3d96a3b9e7"),
                            Name = "FI",
                            Value = 75
                        },
                        new
                        {
                            Id = new Guid("55b7c2f5-2fd7-441a-9081-103ad4cb1c27"),
                            Name = "FR",
                            Value = 76
                        },
                        new
                        {
                            Id = new Guid("139416b3-dafe-4101-9c24-cb13b828698c"),
                            Name = "GF",
                            Value = 77
                        },
                        new
                        {
                            Id = new Guid("d6849a69-8a2e-46cb-bb28-628cdad8b383"),
                            Name = "PF",
                            Value = 78
                        },
                        new
                        {
                            Id = new Guid("df07483e-d71f-43c0-a6cb-76a94bd2856a"),
                            Name = "TF",
                            Value = 79
                        },
                        new
                        {
                            Id = new Guid("46a800df-4a30-41ab-9b64-116f044b2555"),
                            Name = "GA",
                            Value = 80
                        },
                        new
                        {
                            Id = new Guid("c4366b50-90ad-482b-ae3d-a8678996a72a"),
                            Name = "GM",
                            Value = 81
                        },
                        new
                        {
                            Id = new Guid("2a24e370-dda0-476a-8024-744efc2bceea"),
                            Name = "GE",
                            Value = 82
                        },
                        new
                        {
                            Id = new Guid("a8303add-b05c-43cd-9f50-722c16345410"),
                            Name = "DE",
                            Value = 83
                        },
                        new
                        {
                            Id = new Guid("deccbaf1-ef61-487e-a018-74f56104f578"),
                            Name = "GH",
                            Value = 84
                        },
                        new
                        {
                            Id = new Guid("ae7ca192-6be6-4140-967b-fdc3147e807e"),
                            Name = "GI",
                            Value = 85
                        },
                        new
                        {
                            Id = new Guid("21a7ebd7-fe44-4804-b34c-d77bfcae3f7b"),
                            Name = "GR",
                            Value = 86
                        },
                        new
                        {
                            Id = new Guid("791a58e0-cfbd-432d-b286-df1364a3fd12"),
                            Name = "GL",
                            Value = 87
                        },
                        new
                        {
                            Id = new Guid("7cfa4bbc-abf7-49d1-a1cd-fd4d1c14598a"),
                            Name = "GD",
                            Value = 88
                        },
                        new
                        {
                            Id = new Guid("211b37e3-6955-4992-a4f8-b67b4a8ef951"),
                            Name = "GP",
                            Value = 89
                        },
                        new
                        {
                            Id = new Guid("ed032c81-4c2e-4cec-9feb-b3024f0f09a3"),
                            Name = "GU",
                            Value = 90
                        },
                        new
                        {
                            Id = new Guid("a306c837-272e-4c21-b113-d76540a68491"),
                            Name = "GT",
                            Value = 91
                        },
                        new
                        {
                            Id = new Guid("2cfa3ba8-0f62-4b55-8d3b-d43d79bdd635"),
                            Name = "GG",
                            Value = 92
                        },
                        new
                        {
                            Id = new Guid("053cc8d1-65b7-43e1-8b26-28ee3d504d5f"),
                            Name = "GN",
                            Value = 93
                        },
                        new
                        {
                            Id = new Guid("239270a9-b4ff-4eaf-82ac-6c895af9aad7"),
                            Name = "GW",
                            Value = 94
                        },
                        new
                        {
                            Id = new Guid("fddb1513-5487-4d24-b5d1-8912d248c6b8"),
                            Name = "GY",
                            Value = 95
                        },
                        new
                        {
                            Id = new Guid("a0e6d769-6b77-4ab9-a135-b7f56a10582e"),
                            Name = "HT",
                            Value = 96
                        },
                        new
                        {
                            Id = new Guid("6295bcf9-1d52-40dd-9034-c8ac5d36e2a8"),
                            Name = "HM",
                            Value = 97
                        },
                        new
                        {
                            Id = new Guid("8a8f6f0f-a12e-461d-b847-4698e0087833"),
                            Name = "VA",
                            Value = 98
                        },
                        new
                        {
                            Id = new Guid("5ba8464c-a219-46e8-872e-1f3af48987ad"),
                            Name = "HN",
                            Value = 99
                        },
                        new
                        {
                            Id = new Guid("774d35f7-16c8-4638-889a-ec3582b2dac6"),
                            Name = "HK",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("18e998e1-556c-4a54-b3be-e96b9cfd3586"),
                            Name = "HU",
                            Value = 101
                        },
                        new
                        {
                            Id = new Guid("e0677999-66ea-4e8f-8fa2-14879a0a55e2"),
                            Name = "IS",
                            Value = 102
                        },
                        new
                        {
                            Id = new Guid("fdf4b620-b552-4026-8ec9-688044a2f264"),
                            Name = "IN",
                            Value = 103
                        },
                        new
                        {
                            Id = new Guid("26e24b48-f1c3-4324-a216-8648ea8ce96d"),
                            Name = "ID",
                            Value = 104
                        },
                        new
                        {
                            Id = new Guid("80d2a6ec-6831-4b80-97c1-b52d749121bd"),
                            Name = "IR",
                            Value = 105
                        },
                        new
                        {
                            Id = new Guid("3a450dd3-b542-4219-a114-7ce866f0b014"),
                            Name = "IQ",
                            Value = 106
                        },
                        new
                        {
                            Id = new Guid("155f67df-11d5-482f-8078-439a98c0db1b"),
                            Name = "IE",
                            Value = 107
                        },
                        new
                        {
                            Id = new Guid("3653d1fb-b78b-4af3-a07b-f4c7805c4848"),
                            Name = "IM",
                            Value = 108
                        },
                        new
                        {
                            Id = new Guid("81c21925-d860-45df-b717-a7a4c96dca36"),
                            Name = "IL",
                            Value = 109
                        },
                        new
                        {
                            Id = new Guid("b425c8a8-0ee2-416a-9800-dbc2e76a1e02"),
                            Name = "IT",
                            Value = 110
                        },
                        new
                        {
                            Id = new Guid("6d804a88-f71a-4ccc-a4bb-5ef29da5d25e"),
                            Name = "JM",
                            Value = 111
                        },
                        new
                        {
                            Id = new Guid("e25cd762-f8ad-4191-820b-5a21b4a57dd5"),
                            Name = "JP",
                            Value = 112
                        },
                        new
                        {
                            Id = new Guid("30eb8ed6-c1d1-4d00-ad73-e38f312fedb4"),
                            Name = "JE",
                            Value = 113
                        },
                        new
                        {
                            Id = new Guid("25c3c395-a6b9-4555-a893-82febe3e5945"),
                            Name = "JO",
                            Value = 114
                        },
                        new
                        {
                            Id = new Guid("7493d7ea-0a2e-4db5-a79e-72c7099b938b"),
                            Name = "KZ",
                            Value = 115
                        },
                        new
                        {
                            Id = new Guid("10c06541-720b-4914-b3fd-bdb12f692f86"),
                            Name = "KE",
                            Value = 116
                        },
                        new
                        {
                            Id = new Guid("32e1fc1a-fdf6-41b0-b1f4-deedcc1fd3cc"),
                            Name = "KI",
                            Value = 117
                        },
                        new
                        {
                            Id = new Guid("06c6541f-4cec-4fcf-9492-88282a77f9b7"),
                            Name = "KP",
                            Value = 118
                        },
                        new
                        {
                            Id = new Guid("bc668ba6-9f1c-4220-80d2-40ad66f81aaf"),
                            Name = "KR",
                            Value = 119
                        },
                        new
                        {
                            Id = new Guid("0d3a4693-22e5-4b24-916f-ae040bcfdfcb"),
                            Name = "KW",
                            Value = 120
                        },
                        new
                        {
                            Id = new Guid("f05acf2a-f23d-41ea-a757-2d22347670f7"),
                            Name = "KG",
                            Value = 121
                        },
                        new
                        {
                            Id = new Guid("0e208ed9-43f0-4853-b0df-3eee5ca83ca0"),
                            Name = "LA",
                            Value = 122
                        },
                        new
                        {
                            Id = new Guid("9b971e69-8006-4ec1-a6ee-0d5d12e9f8b4"),
                            Name = "LV",
                            Value = 123
                        },
                        new
                        {
                            Id = new Guid("ba52c559-b282-46d8-a912-ec77675f904a"),
                            Name = "LB",
                            Value = 124
                        },
                        new
                        {
                            Id = new Guid("8aa09226-408c-4d45-8097-0f00c6bb8dbd"),
                            Name = "LS",
                            Value = 125
                        },
                        new
                        {
                            Id = new Guid("694871b5-bbd7-4129-b133-444d30d77bce"),
                            Name = "LR",
                            Value = 126
                        },
                        new
                        {
                            Id = new Guid("8e72a54f-12e2-4c5d-a567-90f5d4f75dd6"),
                            Name = "LY",
                            Value = 127
                        },
                        new
                        {
                            Id = new Guid("dce7db69-ac0a-42ea-8fce-2b4759a6cde1"),
                            Name = "LI",
                            Value = 128
                        },
                        new
                        {
                            Id = new Guid("5bd3a292-d554-468a-9fad-ca0cbb5aea0f"),
                            Name = "LT",
                            Value = 129
                        },
                        new
                        {
                            Id = new Guid("13559ef0-ec8f-4df8-90a6-81c292bc5aa7"),
                            Name = "LU",
                            Value = 130
                        },
                        new
                        {
                            Id = new Guid("64d5db60-5b8e-4d28-8759-6684087a9f86"),
                            Name = "MO",
                            Value = 131
                        },
                        new
                        {
                            Id = new Guid("21d5b1c4-503a-4fa8-9169-3896ee99bd03"),
                            Name = "MK",
                            Value = 132
                        },
                        new
                        {
                            Id = new Guid("f5221f09-ded0-4ae7-b0d0-e9638669c5fc"),
                            Name = "MG",
                            Value = 133
                        },
                        new
                        {
                            Id = new Guid("a97120ad-7b3a-496c-8435-dc6efb224ed9"),
                            Name = "MW",
                            Value = 134
                        },
                        new
                        {
                            Id = new Guid("1270ee5e-70c9-4ac0-b2a8-37577e8df1b8"),
                            Name = "MY",
                            Value = 135
                        },
                        new
                        {
                            Id = new Guid("e4c9842b-3d47-4ef9-ae04-c3d0ac788234"),
                            Name = "MV",
                            Value = 136
                        },
                        new
                        {
                            Id = new Guid("704208f6-c664-4b30-9ce5-fe87d53eba6b"),
                            Name = "ML",
                            Value = 137
                        },
                        new
                        {
                            Id = new Guid("1143b247-9398-463f-9748-3b4dd20522f7"),
                            Name = "MT",
                            Value = 138
                        },
                        new
                        {
                            Id = new Guid("338bc858-b9b3-47ca-9c3f-8b06e78bba86"),
                            Name = "MH",
                            Value = 139
                        },
                        new
                        {
                            Id = new Guid("89734048-9854-47fe-80fb-441c2025ebc7"),
                            Name = "MQ",
                            Value = 140
                        },
                        new
                        {
                            Id = new Guid("e9169237-7d99-4557-9079-53e8b8f2fb49"),
                            Name = "MR",
                            Value = 141
                        },
                        new
                        {
                            Id = new Guid("74f18378-7f4d-44a1-a893-91770e6f8597"),
                            Name = "MU",
                            Value = 142
                        },
                        new
                        {
                            Id = new Guid("f68267ec-c571-4eaf-98f1-d367f2c4b43d"),
                            Name = "YT",
                            Value = 143
                        },
                        new
                        {
                            Id = new Guid("c3fbbbc5-4887-446f-8568-43dfc1d53e1e"),
                            Name = "MX",
                            Value = 144
                        },
                        new
                        {
                            Id = new Guid("50287ee0-1f5b-4347-925b-07ed56567581"),
                            Name = "FM",
                            Value = 145
                        },
                        new
                        {
                            Id = new Guid("5d7a008b-c9b0-4471-9c83-0ea1ddfd5045"),
                            Name = "MD",
                            Value = 146
                        },
                        new
                        {
                            Id = new Guid("62ea5c35-3db8-4e8c-912b-7a18aeb343a1"),
                            Name = "MC",
                            Value = 147
                        },
                        new
                        {
                            Id = new Guid("c15a6969-d90a-4849-bd00-ce7824e67424"),
                            Name = "MN",
                            Value = 148
                        },
                        new
                        {
                            Id = new Guid("f0ee72dd-fa17-4601-8795-02d53ebe8889"),
                            Name = "ME",
                            Value = 149
                        },
                        new
                        {
                            Id = new Guid("7fdce1e2-dc0e-43b4-9486-f33306c9a72f"),
                            Name = "MS",
                            Value = 150
                        },
                        new
                        {
                            Id = new Guid("36d7e73b-1e15-4e9b-b6d2-5b252fb89ddb"),
                            Name = "MA",
                            Value = 151
                        },
                        new
                        {
                            Id = new Guid("11819b12-077a-43a4-8417-460c3e3b0851"),
                            Name = "MZ",
                            Value = 152
                        },
                        new
                        {
                            Id = new Guid("4e3e5349-c012-4254-9d55-26ea387b0326"),
                            Name = "MM",
                            Value = 153
                        },
                        new
                        {
                            Id = new Guid("750050aa-c75a-4ef2-a3e4-cfb58ee516b3"),
                            Name = "NA",
                            Value = 154
                        },
                        new
                        {
                            Id = new Guid("4bc003d1-999b-42d1-90b4-846c09e2a638"),
                            Name = "NR",
                            Value = 155
                        },
                        new
                        {
                            Id = new Guid("c5a92c78-2596-4882-b17c-d9732bb7513d"),
                            Name = "NP",
                            Value = 156
                        },
                        new
                        {
                            Id = new Guid("5a368bb5-40c6-4e91-a051-a19932d1f4c5"),
                            Name = "NL",
                            Value = 157
                        },
                        new
                        {
                            Id = new Guid("58acd0f3-7aa1-4b38-b9a8-ebe7525a3dda"),
                            Name = "NC",
                            Value = 158
                        },
                        new
                        {
                            Id = new Guid("3360a2f1-5c5c-4028-9129-2c90131d4ed0"),
                            Name = "NZ",
                            Value = 159
                        },
                        new
                        {
                            Id = new Guid("9775060e-27c6-47d8-bdd0-bb8d24fd9897"),
                            Name = "NI",
                            Value = 160
                        },
                        new
                        {
                            Id = new Guid("8b158e33-0b9a-46c3-ad01-e8e064f375e5"),
                            Name = "NE",
                            Value = 161
                        },
                        new
                        {
                            Id = new Guid("2ca7c0a3-c56a-4502-94da-99aeeea27b8c"),
                            Name = "NG",
                            Value = 162
                        },
                        new
                        {
                            Id = new Guid("d3822fc6-1512-49cc-8975-e2086cdfb0bf"),
                            Name = "NU",
                            Value = 163
                        },
                        new
                        {
                            Id = new Guid("27d91671-6aac-4c86-b749-69003b7fba9a"),
                            Name = "NF",
                            Value = 164
                        },
                        new
                        {
                            Id = new Guid("c67919ca-db71-4bfa-ace1-32433e22f1e9"),
                            Name = "MP",
                            Value = 165
                        },
                        new
                        {
                            Id = new Guid("77eea453-e268-4c0d-a06c-d09b16e977f8"),
                            Name = "NO",
                            Value = 166
                        },
                        new
                        {
                            Id = new Guid("ed28ee11-e23d-4103-b45a-db76b98ef66a"),
                            Name = "OM",
                            Value = 167
                        },
                        new
                        {
                            Id = new Guid("734308af-c2ca-4d37-a6a3-4bd245e010ba"),
                            Name = "PK",
                            Value = 168
                        },
                        new
                        {
                            Id = new Guid("bcf91ffc-37d1-4cac-970c-b0c47f24fa01"),
                            Name = "PW",
                            Value = 169
                        },
                        new
                        {
                            Id = new Guid("78f2a19e-d0c1-4968-b510-6a053c31b0c4"),
                            Name = "PS",
                            Value = 170
                        },
                        new
                        {
                            Id = new Guid("0f0ccfee-e26e-479b-9e8a-ff219147e72e"),
                            Name = "PA",
                            Value = 171
                        },
                        new
                        {
                            Id = new Guid("e4e334d8-9e9f-41e2-8964-e4f5c9697b99"),
                            Name = "PG",
                            Value = 172
                        },
                        new
                        {
                            Id = new Guid("d520b651-c391-4faf-b92f-d00d0d9965d7"),
                            Name = "PY",
                            Value = 173
                        },
                        new
                        {
                            Id = new Guid("415f226e-4d82-42c4-95dd-020e929aa94c"),
                            Name = "PE",
                            Value = 174
                        },
                        new
                        {
                            Id = new Guid("f04003c8-e13b-4c43-aacc-112fba6b7a52"),
                            Name = "PH",
                            Value = 175
                        },
                        new
                        {
                            Id = new Guid("8e5aea51-e9d4-4028-8dfe-fbbae29db819"),
                            Name = "PN",
                            Value = 176
                        },
                        new
                        {
                            Id = new Guid("181d789b-3433-403c-b782-5fca65b83251"),
                            Name = "PL",
                            Value = 177
                        },
                        new
                        {
                            Id = new Guid("c128323a-065c-4f63-bed8-20ac766233f1"),
                            Name = "PT",
                            Value = 178
                        },
                        new
                        {
                            Id = new Guid("75d84d0b-5d2b-423f-8236-88dd0cc5c58e"),
                            Name = "PR",
                            Value = 179
                        },
                        new
                        {
                            Id = new Guid("97f546fd-c226-488a-9820-5a4ef96004ab"),
                            Name = "QA",
                            Value = 180
                        },
                        new
                        {
                            Id = new Guid("bbd02f2e-49fa-485b-bcb8-9cace62a7b8c"),
                            Name = "RE",
                            Value = 181
                        },
                        new
                        {
                            Id = new Guid("c5fd82d9-d8a7-49ea-a0cc-13870a8842a1"),
                            Name = "RO",
                            Value = 182
                        },
                        new
                        {
                            Id = new Guid("612b4105-151b-47f7-aaf6-ef15559c9ff0"),
                            Name = "RU",
                            Value = 183
                        },
                        new
                        {
                            Id = new Guid("3b480777-f466-47b8-9500-603d6f145f20"),
                            Name = "RW",
                            Value = 184
                        },
                        new
                        {
                            Id = new Guid("3573e823-bdc6-4e7e-8ee3-52531c2dfaab"),
                            Name = "BL",
                            Value = 185
                        },
                        new
                        {
                            Id = new Guid("86960811-d456-420b-873b-28962a547dbf"),
                            Name = "SH",
                            Value = 186
                        },
                        new
                        {
                            Id = new Guid("9b5d34ef-f407-489f-9343-91fd3dfb233f"),
                            Name = "KN",
                            Value = 187
                        },
                        new
                        {
                            Id = new Guid("fc39c320-9142-43ef-912b-9990a5b548d6"),
                            Name = "LC",
                            Value = 188
                        },
                        new
                        {
                            Id = new Guid("4047a5c1-9b4b-417c-9a56-4fb811ebd051"),
                            Name = "MF",
                            Value = 189
                        },
                        new
                        {
                            Id = new Guid("cd878fe1-140d-422e-993a-3f2d16c8805a"),
                            Name = "PM",
                            Value = 190
                        },
                        new
                        {
                            Id = new Guid("86ca958d-c720-4c6d-b3d7-7da7140c29cc"),
                            Name = "VC",
                            Value = 191
                        },
                        new
                        {
                            Id = new Guid("8d9cb652-b271-428b-9d8a-4cd90adcd4e9"),
                            Name = "WS",
                            Value = 192
                        },
                        new
                        {
                            Id = new Guid("16ab42ff-8ddc-4f25-a64c-c0c23a8c5f59"),
                            Name = "SM",
                            Value = 193
                        },
                        new
                        {
                            Id = new Guid("8d576da4-f840-40ce-a9b6-33bb8fb05624"),
                            Name = "ST",
                            Value = 194
                        },
                        new
                        {
                            Id = new Guid("11de18e3-c37b-4401-97b0-48d8b0fa8176"),
                            Name = "SA",
                            Value = 195
                        },
                        new
                        {
                            Id = new Guid("7f66abe7-2a21-4807-9fe1-b740facd62e0"),
                            Name = "SN",
                            Value = 196
                        },
                        new
                        {
                            Id = new Guid("efae3600-d8a4-4312-afa6-2a58f73b18b2"),
                            Name = "RS",
                            Value = 197
                        },
                        new
                        {
                            Id = new Guid("bcfa6a62-0a90-41ca-9270-027da98d1c5d"),
                            Name = "SC",
                            Value = 198
                        },
                        new
                        {
                            Id = new Guid("84a1a222-b9a3-40b0-b9bd-5f206aae3380"),
                            Name = "SL",
                            Value = 199
                        },
                        new
                        {
                            Id = new Guid("7333b43e-65a1-42da-81aa-ab0261bc1949"),
                            Name = "SG",
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("2fe39403-c091-40d7-a13c-f45dc9fdc290"),
                            Name = "SX",
                            Value = 201
                        },
                        new
                        {
                            Id = new Guid("0fd57a12-26c5-4105-b3e0-d12502d781fc"),
                            Name = "SK",
                            Value = 202
                        },
                        new
                        {
                            Id = new Guid("0c4bbd83-0c25-4b9a-8fb6-8d34c448ed6f"),
                            Name = "SI",
                            Value = 203
                        },
                        new
                        {
                            Id = new Guid("5a118659-a2c5-4c64-9d23-2e5db25fdd6c"),
                            Name = "SB",
                            Value = 204
                        },
                        new
                        {
                            Id = new Guid("dd4f3d0f-f8fd-4660-8e21-36265f4d5cb9"),
                            Name = "SO",
                            Value = 205
                        },
                        new
                        {
                            Id = new Guid("934f1188-3d4f-4311-925b-95b82b656242"),
                            Name = "ZA",
                            Value = 206
                        },
                        new
                        {
                            Id = new Guid("c9675524-ebfc-4d16-a40e-5b479d9600bf"),
                            Name = "GS",
                            Value = 207
                        },
                        new
                        {
                            Id = new Guid("118ba47e-d209-482b-b13b-c51507d5c9e5"),
                            Name = "SS",
                            Value = 208
                        },
                        new
                        {
                            Id = new Guid("77058d59-6cd1-4ced-93ba-7f2fa1fcea73"),
                            Name = "ES",
                            Value = 209
                        },
                        new
                        {
                            Id = new Guid("3f925f3c-f923-47cb-9047-6828e697857c"),
                            Name = "LK",
                            Value = 210
                        },
                        new
                        {
                            Id = new Guid("c8b13b9a-36f8-40ad-985d-70e1ad27b8a6"),
                            Name = "SD",
                            Value = 211
                        },
                        new
                        {
                            Id = new Guid("f164518f-2a99-497d-9a2e-47ec9f16ce38"),
                            Name = "SR",
                            Value = 212
                        },
                        new
                        {
                            Id = new Guid("8d2de3fa-b8af-45c6-9f83-c11987709e83"),
                            Name = "SJ",
                            Value = 213
                        },
                        new
                        {
                            Id = new Guid("4d5e4b5d-ab4a-4e85-bd0f-78d0fe33d036"),
                            Name = "SZ",
                            Value = 214
                        },
                        new
                        {
                            Id = new Guid("922f9763-699a-45e2-9e59-e5ab3ff2ae25"),
                            Name = "SE",
                            Value = 215
                        },
                        new
                        {
                            Id = new Guid("2f1eff27-e291-420a-b33a-2fcc90fece61"),
                            Name = "CH",
                            Value = 216
                        },
                        new
                        {
                            Id = new Guid("9a4f3a9e-464b-49b7-bd0b-f80caae39e86"),
                            Name = "SY",
                            Value = 217
                        },
                        new
                        {
                            Id = new Guid("7bf44862-2699-4965-a736-ad6774a7a43f"),
                            Name = "TW",
                            Value = 218
                        },
                        new
                        {
                            Id = new Guid("644aaf2c-b35f-4f35-bae2-9d42bb217cf7"),
                            Name = "TJ",
                            Value = 219
                        },
                        new
                        {
                            Id = new Guid("209c6e53-b31d-423a-860a-b3371bfc2084"),
                            Name = "TZ",
                            Value = 220
                        },
                        new
                        {
                            Id = new Guid("8950f339-2769-441b-a9b8-1a8106320b9f"),
                            Name = "TH",
                            Value = 221
                        },
                        new
                        {
                            Id = new Guid("0946c5d4-8b53-4852-8bb3-0accc3deebac"),
                            Name = "TL",
                            Value = 222
                        },
                        new
                        {
                            Id = new Guid("2ba286ce-8b1b-4ceb-8314-6cad68925fd5"),
                            Name = "TG",
                            Value = 223
                        },
                        new
                        {
                            Id = new Guid("5470eb7c-c2dd-4b37-a261-d1060de399cf"),
                            Name = "TK",
                            Value = 224
                        },
                        new
                        {
                            Id = new Guid("2ff2abe7-4d46-4ddb-aceb-f7156ec94dcb"),
                            Name = "TO",
                            Value = 225
                        },
                        new
                        {
                            Id = new Guid("ca86647a-f8da-4bb3-9304-531247544aa3"),
                            Name = "TT",
                            Value = 226
                        },
                        new
                        {
                            Id = new Guid("dcc2b781-ef65-4406-b94f-91e5f236c104"),
                            Name = "TN",
                            Value = 227
                        },
                        new
                        {
                            Id = new Guid("e1bc8935-6bea-4c34-b289-980c861d503e"),
                            Name = "TR",
                            Value = 228
                        },
                        new
                        {
                            Id = new Guid("daaf5442-94e5-493d-bd4b-66c3978dca78"),
                            Name = "TM",
                            Value = 229
                        },
                        new
                        {
                            Id = new Guid("e795e160-30ae-49f1-9fb6-ef54e9dea3d2"),
                            Name = "TC",
                            Value = 230
                        },
                        new
                        {
                            Id = new Guid("84aae4be-ba58-428a-a310-34aaf4992b5a"),
                            Name = "TV",
                            Value = 231
                        },
                        new
                        {
                            Id = new Guid("9e44d2f1-6d7b-4335-b6ab-d83316d249ec"),
                            Name = "UG",
                            Value = 232
                        },
                        new
                        {
                            Id = new Guid("84aa5a15-ffc2-4308-937e-e3a37b5f075f"),
                            Name = "UA",
                            Value = 233
                        },
                        new
                        {
                            Id = new Guid("1c63855c-238e-4b25-b2ff-f2c8cb594b12"),
                            Name = "AE",
                            Value = 234
                        },
                        new
                        {
                            Id = new Guid("513b4ff3-9274-4605-a6cd-7ab5d6fe7c73"),
                            Name = "GB",
                            Value = 235
                        },
                        new
                        {
                            Id = new Guid("22091318-cd6b-4049-9911-efce3eeb3deb"),
                            Name = "US",
                            Value = 236
                        },
                        new
                        {
                            Id = new Guid("1eddaf41-9746-46c0-868b-b4303bfa007b"),
                            Name = "UM",
                            Value = 237
                        },
                        new
                        {
                            Id = new Guid("787e5033-5f97-4e81-8953-a1b41724dc0f"),
                            Name = "UY",
                            Value = 238
                        },
                        new
                        {
                            Id = new Guid("3633ea89-ac98-4a77-ba6d-f4744929132b"),
                            Name = "UZ",
                            Value = 239
                        },
                        new
                        {
                            Id = new Guid("e2e8f63c-f1a4-4135-bd23-056730a22a52"),
                            Name = "VU",
                            Value = 240
                        },
                        new
                        {
                            Id = new Guid("fdf16a7e-6f06-47a8-bd53-da2ddd31cdec"),
                            Name = "VE",
                            Value = 241
                        },
                        new
                        {
                            Id = new Guid("97eca2aa-9a97-4365-8356-50d49bd58034"),
                            Name = "VN",
                            Value = 242
                        },
                        new
                        {
                            Id = new Guid("70fbe487-a108-4bf4-a79f-02287d4331aa"),
                            Name = "VG",
                            Value = 243
                        },
                        new
                        {
                            Id = new Guid("221ec5b8-f75b-4063-85d7-3de7ca4e0092"),
                            Name = "VI",
                            Value = 244
                        },
                        new
                        {
                            Id = new Guid("4a585fd3-7ffa-4f89-a3eb-c8f7d6bdfa59"),
                            Name = "WF",
                            Value = 245
                        },
                        new
                        {
                            Id = new Guid("4ca05911-3157-4bfb-a678-f424cb655b98"),
                            Name = "EH",
                            Value = 246
                        },
                        new
                        {
                            Id = new Guid("09067e50-dab7-44fe-b5d9-61b734bc0ede"),
                            Name = "YE",
                            Value = 247
                        },
                        new
                        {
                            Id = new Guid("86c57c4d-8f12-45b5-8581-946c3fc3d481"),
                            Name = "ZM",
                            Value = 248
                        },
                        new
                        {
                            Id = new Guid("9d647981-183d-4844-a312-4f26695b356e"),
                            Name = "ZW",
                            Value = 249
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MachineDimensionsType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a4a1633-b058-4d8a-a066-b83d6dc63e58"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("ff77b51e-1019-49fb-9837-a054277eea69"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("b0ba1076-32e9-4683-9daa-4332734b5cc7"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MillingMachineTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a26ac0e4-677a-48fc-8384-c9454f92778e"),
                            Name = "TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("13daa247-12f7-4885-966e-276dc3722694"),
                            Name = "TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("5fdcf81d-00f5-45b6-91f4-0b19bceb8550"),
                            Name = "TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("c83bacb5-c1cd-4b25-9f07-29360d29d166"),
                            Name = "TYPE_4",
                            Value = 3
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("OtherTechnologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2cfcbb75-3a13-4eae-8c7f-7953f198d11e"),
                            Name = "DeepHoleDrilling",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("d424f88d-3d6e-44f4-9fed-d5917a39e52d"),
                            Name = "ThreadsM",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("e4a35ad3-90ed-4de9-808a-e4780cba505b"),
                            Name = "ThreadsTr",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("55dd3dfc-c30e-4eeb-8ee5-e39a99b79f93"),
                            Name = "Toothings",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("c2fd923a-ab53-4472-a622-3128ac911a7e"),
                            Name = "Engravings",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("3a09b1c8-5c5b-463f-8dfa-352f2cf0f947"),
                            Name = "LaserMarking",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("3f3ddc24-6a9a-42e5-870e-fe7feb7a5806"),
                            Name = "Knurling",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("5310b489-8165-4fc9-970b-6eeb03507ed9"),
                            Name = "Annealing",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("6b33a4e0-e41a-48a4-86b7-3710e5d9915f"),
                            Name = "Other",
                            Value = 8
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("MillingMachineDimensionsTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MillingMachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MillingMachineDimensionsTypeId");

                    b.HasIndex("MillingMachineTypeId");

                    b.ToTable("MillingMachine");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MillingMachineDimensionsTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f32bad09-eb6c-45bf-a0ef-abea908b330c"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("638e7164-0cb9-4a37-a716-2af0437d3475"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("5ce52734-cdc6-4b7f-8180-c9a1a5b357db"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TurningMachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TurningMachineTypeId");

                    b.ToTable("TurningMachines");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.TurningMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("TurningMachineTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("94857418-d240-44a5-ba38-4b0ed0e13d9a"),
                            Name = "TURNING_MACHINE_TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("36f8452a-176a-4ea8-ad8f-f9f8ecfe3c58"),
                            Name = "TURNING_MACHINE_TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("d61e11f4-ce6f-4e98-a1b7-5c88623052b5"),
                            Name = "TURNING_MACHINE_TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("e8706c40-4e55-4b7d-9430-2b049c4fef24"),
                            Name = "TURNING_MACHINE_TYPE_4",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("ae33f04c-5c84-4bcb-8f21-9515fd4d5082"),
                            Name = "TURNING_MACHINE_TYPE_5",
                            Value = 4
                        });
                });

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", null)
                        .WithMany()
                        .HasForeignKey("OtherTechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", "AddressType")
                        .WithMany()
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCodeType", "CountryCodeType")
                        .WithMany()
                        .HasForeignKey("CountryCodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressType");

                    b.Navigation("CountryCodeType");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySizeType", "CompanySizeType")
                        .WithMany()
                        .HasForeignKey("CompanySizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySizeType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithOne("CustomerAdditionalInfo")
                        .HasForeignKey("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("MillingMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", "MillingMachineDimensionsType")
                        .WithMany()
                        .HasForeignKey("MillingMachineDimensionsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", "MillingMachineType")
                        .WithMany()
                        .HasForeignKey("MillingMachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MillingMachineDimensionsType");

                    b.Navigation("MillingMachineType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Registration", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithOne("Registration")
                        .HasForeignKey("Oroox.SubSuppliers.Domain.Entities.Registration", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("TurningMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.TurningMachineType", "TurningMachineType")
                        .WithMany()
                        .HasForeignKey("TurningMachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TurningMachineType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerAdditionalInfo");

                    b.Navigation("MillingMachines");

                    b.Navigation("Registration");

                    b.Navigation("TurningMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
