// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oroox.SubSuppliers.Domain;

namespace Oroox.SubSuppliers.Domain.Migrations
{
    [DbContext(typeof(SubSuppliersContext))]
    [Migration("20210517113742_Customer")]
    partial class Customer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.Property<Guid>("CertificationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CertificationsId", "CustomersId");

                    b.HasIndex("CustomersId");

                    b.ToTable("CertificationCustomer");
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.Property<Guid>("CustomersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OtherTechnologiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomersId", "OtherTechnologiesId");

                    b.HasIndex("OtherTechnologiesId");

                    b.ToTable("CustomerOtherTechnology");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("Certification");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b931f643-f1c1-41c9-84fa-a8b55c460810"),
                            Name = "ISO9001",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("389144fc-ee57-4eef-8c65-158c5b7cc3e3"),
                            Name = "ISO14001",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("00c29f75-f554-42f2-b140-112c5d1f9b39"),
                            Name = "ISO13485",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("ee7da6e4-ce16-40ba-bbd2-4a2e9cb19826"),
                            Name = "ITAF16949",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("ac86f580-97a2-4f8f-b7b2-13aca3726c36"),
                            Name = "EN9100",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("8fa38536-e68e-4a42-9ea6-dd66feadf9c4"),
                            Name = "Other",
                            Value = 5
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<Guid>("AddressTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CountryCodeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId");

                    b.HasIndex("CountryCodeTypeId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanySizeTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerAdditionalInfoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanySizeTypeId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageAndFastestLeadTimeMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageAndFastestLeadTimeTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesMilling")
                        .HasColumnType("float");

                    b.Property<double?>("AverageMinimalSurfaceQualitiesTurning")
                        .HasColumnType("float");

                    b.Property<double?>("AverageWorkingHoursPerWeek")
                        .HasColumnType("float");

                    b.Property<bool?>("CanUseStepFiles")
                        .HasColumnType("bit");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialCharacteristics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialTolerances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkingShiftsPerDay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerAdditionalInfo");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("AddressType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6267f0a1-4a65-45a1-9420-7fe742fad6c3"),
                            Name = "Shipping",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("bc25d13f-99d1-4458-86fc-c862d9c8e31f"),
                            Name = "Billing",
                            Value = 1
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySizeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("CompanySizeTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa8fd2e1-0755-4236-857f-bbff5098c83b"),
                            Name = "LessThan10",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("4e55f870-7290-42a8-90a2-89e88c44ed81"),
                            Name = "LessThan25",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("d7eea6cd-6ecc-4166-9118-b9374bdd8211"),
                            Name = "LessThan50",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("bdcd87b6-603a-47ff-94ab-b3073e3017b2"),
                            Name = "LessThan100",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("4a645606-ba1c-4867-88f7-495a61507200"),
                            Name = "MoreThan100",
                            Value = 101
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCodeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("CountryCodeType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c390510c-556e-47ab-8f2f-c027669585a8"),
                            Name = "AF",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("2b3cb465-a06f-4481-b56a-745d6b3f0672"),
                            Name = "AX",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("393db64e-a658-4a04-86d2-5675e64c3754"),
                            Name = "AL",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("1636db9f-b1ea-4f82-ba84-9b06e97bab25"),
                            Name = "DZ",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("4e52528e-5219-4aec-ba3b-155685424e0d"),
                            Name = "AS",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("c0a7f8ea-635e-45bd-af59-85ad4b78c7bb"),
                            Name = "AD",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("eab18277-909f-4f4f-ae23-2444fe18c217"),
                            Name = "AO",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("0609f999-8c44-4adb-a6b6-1b9bfc87a26b"),
                            Name = "AI",
                            Value = 8
                        },
                        new
                        {
                            Id = new Guid("bb9e200e-d150-494f-ad49-5d14f309a776"),
                            Name = "AQ",
                            Value = 9
                        },
                        new
                        {
                            Id = new Guid("790af826-7332-4fff-ae32-ca36f2fa0111"),
                            Name = "AG",
                            Value = 10
                        },
                        new
                        {
                            Id = new Guid("44ea2527-690c-41b3-8276-d5d7e4a71404"),
                            Name = "AR",
                            Value = 11
                        },
                        new
                        {
                            Id = new Guid("317d9bc5-cef1-404a-b0b9-3427600b016e"),
                            Name = "AM",
                            Value = 12
                        },
                        new
                        {
                            Id = new Guid("097329bd-834c-4f14-a2f3-6acc4962f608"),
                            Name = "AW",
                            Value = 13
                        },
                        new
                        {
                            Id = new Guid("9d0ee05c-8a68-44c7-9b8c-c0cc45737a68"),
                            Name = "AU",
                            Value = 14
                        },
                        new
                        {
                            Id = new Guid("4dd3640f-1239-4682-b21d-105e6c0c7d0a"),
                            Name = "AT",
                            Value = 15
                        },
                        new
                        {
                            Id = new Guid("465f17be-8c4c-4458-999c-e181223b5469"),
                            Name = "AZ",
                            Value = 16
                        },
                        new
                        {
                            Id = new Guid("fc2592a1-44d8-414c-b3be-c9e3395724a2"),
                            Name = "BS",
                            Value = 17
                        },
                        new
                        {
                            Id = new Guid("7e8ce6aa-534b-4af1-ae99-fe10a1d7d01b"),
                            Name = "BH",
                            Value = 18
                        },
                        new
                        {
                            Id = new Guid("dedbfca3-7bfa-4656-93b7-2e5c87ebb426"),
                            Name = "BD",
                            Value = 19
                        },
                        new
                        {
                            Id = new Guid("f33e796c-8cd2-47b9-88e3-c6afaf61e8f2"),
                            Name = "BB",
                            Value = 20
                        },
                        new
                        {
                            Id = new Guid("73727b52-e484-4878-8bb2-2699d2d8bc28"),
                            Name = "BY",
                            Value = 21
                        },
                        new
                        {
                            Id = new Guid("b64f23a4-9c43-471a-a83a-6cdb8b17988a"),
                            Name = "BE",
                            Value = 22
                        },
                        new
                        {
                            Id = new Guid("adc920d1-0827-476c-b42d-694d1f507cd4"),
                            Name = "BZ",
                            Value = 23
                        },
                        new
                        {
                            Id = new Guid("5f9490a9-b14c-4c3f-81d7-46373cbf55e3"),
                            Name = "BJ",
                            Value = 24
                        },
                        new
                        {
                            Id = new Guid("7e8001e4-7cb5-418b-bf0e-a9b8806b1aa3"),
                            Name = "BM",
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("be741de3-fb65-422a-9278-5c3bfa5750ff"),
                            Name = "BT",
                            Value = 26
                        },
                        new
                        {
                            Id = new Guid("6a17e070-6a00-4892-95ee-1a59da1ffdc5"),
                            Name = "BO",
                            Value = 27
                        },
                        new
                        {
                            Id = new Guid("bf3e3fba-560c-4616-9f9d-83e0c608efb4"),
                            Name = "BQ",
                            Value = 28
                        },
                        new
                        {
                            Id = new Guid("67ced096-6146-4494-b218-b5a05bff8ba3"),
                            Name = "BA",
                            Value = 29
                        },
                        new
                        {
                            Id = new Guid("37e9b6d0-e880-4bf8-9f04-180f04136fcb"),
                            Name = "BW",
                            Value = 30
                        },
                        new
                        {
                            Id = new Guid("94b94540-cddc-4f4b-a7a2-bc620a33a00d"),
                            Name = "BV",
                            Value = 31
                        },
                        new
                        {
                            Id = new Guid("7c75b5ec-b74d-47e3-9809-b3e5143eb9ad"),
                            Name = "BR",
                            Value = 32
                        },
                        new
                        {
                            Id = new Guid("a3b1ce21-3aaa-4711-ba10-e120a16fa7ec"),
                            Name = "IO",
                            Value = 33
                        },
                        new
                        {
                            Id = new Guid("7c3aa7cb-5432-4c58-b575-9b08d6bcf160"),
                            Name = "BN",
                            Value = 34
                        },
                        new
                        {
                            Id = new Guid("033d322e-e4e5-4c0a-bca5-eed14fbace19"),
                            Name = "BG",
                            Value = 35
                        },
                        new
                        {
                            Id = new Guid("f67accf5-7ed7-4ea7-8cdb-38220de5c9d6"),
                            Name = "BF",
                            Value = 36
                        },
                        new
                        {
                            Id = new Guid("e5f875d6-e17b-409e-92a7-fa7ef90ad055"),
                            Name = "BI",
                            Value = 37
                        },
                        new
                        {
                            Id = new Guid("3bb65d00-c5a8-4abf-9dea-c8db5999e4dd"),
                            Name = "CV",
                            Value = 38
                        },
                        new
                        {
                            Id = new Guid("e336694a-131b-4bcf-96ac-fd9408181150"),
                            Name = "KH",
                            Value = 39
                        },
                        new
                        {
                            Id = new Guid("c6de6b70-023e-4190-84e3-ab11e61ff808"),
                            Name = "CM",
                            Value = 40
                        },
                        new
                        {
                            Id = new Guid("1022c57e-cb71-4394-851b-fa9f398d6ac8"),
                            Name = "CA",
                            Value = 41
                        },
                        new
                        {
                            Id = new Guid("1e269890-2008-4f70-8264-52aec3633002"),
                            Name = "KY",
                            Value = 42
                        },
                        new
                        {
                            Id = new Guid("11b8ea45-052f-4189-9762-3dbd847ee31e"),
                            Name = "CF",
                            Value = 43
                        },
                        new
                        {
                            Id = new Guid("9194ce8e-1835-4829-a4ba-e0b6ab2ed39f"),
                            Name = "TD",
                            Value = 44
                        },
                        new
                        {
                            Id = new Guid("be364f25-b51f-4fda-a1c6-5536a7a4af59"),
                            Name = "CL",
                            Value = 45
                        },
                        new
                        {
                            Id = new Guid("a7cd4bea-5b0f-4f4c-860a-603e97fa8e2c"),
                            Name = "CN",
                            Value = 46
                        },
                        new
                        {
                            Id = new Guid("38986822-49c9-419b-beff-76d46064f0d6"),
                            Name = "CX",
                            Value = 47
                        },
                        new
                        {
                            Id = new Guid("2368a042-cdc0-40b7-92af-6a3139cc2e7f"),
                            Name = "CC",
                            Value = 48
                        },
                        new
                        {
                            Id = new Guid("cea3bcea-f131-4e28-9137-f8e07089b268"),
                            Name = "CO",
                            Value = 49
                        },
                        new
                        {
                            Id = new Guid("87149cc5-2bb3-4f56-bcee-e32f1955e9c8"),
                            Name = "KM",
                            Value = 50
                        },
                        new
                        {
                            Id = new Guid("4e1f8b63-a570-49e3-a57d-626fc791dc5a"),
                            Name = "CG",
                            Value = 51
                        },
                        new
                        {
                            Id = new Guid("e1d4b1b5-8456-4060-9cc1-48ae68f3f6d8"),
                            Name = "CD",
                            Value = 52
                        },
                        new
                        {
                            Id = new Guid("13cf6a8c-815c-421c-917b-974de304e6bd"),
                            Name = "CK",
                            Value = 53
                        },
                        new
                        {
                            Id = new Guid("7531e01f-a6f8-4b5c-ac5d-058b3d8497f1"),
                            Name = "CR",
                            Value = 54
                        },
                        new
                        {
                            Id = new Guid("c37e40f2-f392-4941-abf8-018c8af79f55"),
                            Name = "CI",
                            Value = 55
                        },
                        new
                        {
                            Id = new Guid("1b7a16f9-5668-477b-b54d-6decda4fe4b4"),
                            Name = "HR",
                            Value = 56
                        },
                        new
                        {
                            Id = new Guid("2a3c4cd6-3812-45c7-8739-afcb9686ae29"),
                            Name = "CU",
                            Value = 57
                        },
                        new
                        {
                            Id = new Guid("833a739c-6d18-47e8-8e9e-5419ca426bcb"),
                            Name = "CW",
                            Value = 58
                        },
                        new
                        {
                            Id = new Guid("f035afb5-98fb-40a4-9b73-56621331ffe8"),
                            Name = "CY",
                            Value = 59
                        },
                        new
                        {
                            Id = new Guid("399f2b95-0bf6-4278-ab22-f98406cc1c9c"),
                            Name = "CZ",
                            Value = 60
                        },
                        new
                        {
                            Id = new Guid("dd2dbd41-90cc-45be-bd4d-d29eb13beb1c"),
                            Name = "DK",
                            Value = 61
                        },
                        new
                        {
                            Id = new Guid("3a0cfde5-430a-47be-baa1-8f8e244f980b"),
                            Name = "DJ",
                            Value = 62
                        },
                        new
                        {
                            Id = new Guid("64800852-4ea6-4cab-b3c1-b285ca42ceba"),
                            Name = "DM",
                            Value = 63
                        },
                        new
                        {
                            Id = new Guid("ae15bce0-48cb-4fd3-b956-05740c7172b7"),
                            Name = "DO",
                            Value = 64
                        },
                        new
                        {
                            Id = new Guid("19f8bba6-af5f-4a29-bdb0-676505ed01a0"),
                            Name = "EC",
                            Value = 65
                        },
                        new
                        {
                            Id = new Guid("74f0d480-c848-4755-b495-afdf1946f13e"),
                            Name = "EG",
                            Value = 66
                        },
                        new
                        {
                            Id = new Guid("79d76b35-1ac0-4341-81c8-e1d91d00efcf"),
                            Name = "SV",
                            Value = 67
                        },
                        new
                        {
                            Id = new Guid("83132b8f-aaf8-4586-9f55-8e97c1c8ffec"),
                            Name = "GQ",
                            Value = 68
                        },
                        new
                        {
                            Id = new Guid("44bf5df2-0957-446e-a60d-fe873512cf9a"),
                            Name = "ER",
                            Value = 69
                        },
                        new
                        {
                            Id = new Guid("ccaa9918-976c-4ff3-bc81-d972a974f4ae"),
                            Name = "EE",
                            Value = 70
                        },
                        new
                        {
                            Id = new Guid("f08289f7-fdb5-4067-8be5-00309ac81144"),
                            Name = "ET",
                            Value = 71
                        },
                        new
                        {
                            Id = new Guid("1414ea5c-d1c2-42cb-be1c-968bafd2c9e1"),
                            Name = "FK",
                            Value = 72
                        },
                        new
                        {
                            Id = new Guid("b146f68d-9f85-4164-888c-79cf9b19d5e8"),
                            Name = "FO",
                            Value = 73
                        },
                        new
                        {
                            Id = new Guid("458a196c-13f3-4ca2-a5b2-3c7c485696a0"),
                            Name = "FJ",
                            Value = 74
                        },
                        new
                        {
                            Id = new Guid("a6446357-eae0-412f-abb4-d55db92a35c5"),
                            Name = "FI",
                            Value = 75
                        },
                        new
                        {
                            Id = new Guid("5b59493b-7093-49a0-870e-f391cdde8b1d"),
                            Name = "FR",
                            Value = 76
                        },
                        new
                        {
                            Id = new Guid("a18699c3-e820-4be9-9f89-d1c73cb5aa41"),
                            Name = "GF",
                            Value = 77
                        },
                        new
                        {
                            Id = new Guid("ffc328d8-94ba-400e-970d-28f2c205293b"),
                            Name = "PF",
                            Value = 78
                        },
                        new
                        {
                            Id = new Guid("58d5df86-0dd1-4d35-ba52-650e37a9ce69"),
                            Name = "TF",
                            Value = 79
                        },
                        new
                        {
                            Id = new Guid("56015486-2a19-47ba-aba3-ee8510c2f51f"),
                            Name = "GA",
                            Value = 80
                        },
                        new
                        {
                            Id = new Guid("6d683a54-e47c-4e13-be7b-6c3c4e6e3e8b"),
                            Name = "GM",
                            Value = 81
                        },
                        new
                        {
                            Id = new Guid("f161e5ae-53b6-4cb6-b156-ebcf9c7b68c1"),
                            Name = "GE",
                            Value = 82
                        },
                        new
                        {
                            Id = new Guid("040825c4-364f-48c7-bc99-e0869b21ea2b"),
                            Name = "DE",
                            Value = 83
                        },
                        new
                        {
                            Id = new Guid("b1ad9148-509f-421d-a6ae-1e58e74ba8fb"),
                            Name = "GH",
                            Value = 84
                        },
                        new
                        {
                            Id = new Guid("4a1b13e4-90b5-439b-8e08-bd91dedf31a8"),
                            Name = "GI",
                            Value = 85
                        },
                        new
                        {
                            Id = new Guid("88062106-508c-4647-8b32-25f310f78da6"),
                            Name = "GR",
                            Value = 86
                        },
                        new
                        {
                            Id = new Guid("ed6ecf1f-6f75-427c-95be-5898414c3808"),
                            Name = "GL",
                            Value = 87
                        },
                        new
                        {
                            Id = new Guid("f7eb59aa-4559-45c8-8d17-65233477f66d"),
                            Name = "GD",
                            Value = 88
                        },
                        new
                        {
                            Id = new Guid("e78cd924-bb7f-41e1-8cfd-5fa4a83eb442"),
                            Name = "GP",
                            Value = 89
                        },
                        new
                        {
                            Id = new Guid("e1c9256c-bd50-4904-88fc-693a92845a57"),
                            Name = "GU",
                            Value = 90
                        },
                        new
                        {
                            Id = new Guid("a2ea9a5b-1230-4a68-88e7-58f3fd741bf6"),
                            Name = "GT",
                            Value = 91
                        },
                        new
                        {
                            Id = new Guid("c94f7e2b-edf0-4ac9-ba2e-24935c52dc8e"),
                            Name = "GG",
                            Value = 92
                        },
                        new
                        {
                            Id = new Guid("c60f40d0-87a4-46cd-8c42-3d101e88378e"),
                            Name = "GN",
                            Value = 93
                        },
                        new
                        {
                            Id = new Guid("7ebd20a9-1ca7-4dc9-8c6b-59b769bc353f"),
                            Name = "GW",
                            Value = 94
                        },
                        new
                        {
                            Id = new Guid("56cc2d4c-7e0d-462d-9a64-f39481ee20f3"),
                            Name = "GY",
                            Value = 95
                        },
                        new
                        {
                            Id = new Guid("8553750d-22c3-464d-8fd1-d01276b9cf1a"),
                            Name = "HT",
                            Value = 96
                        },
                        new
                        {
                            Id = new Guid("3d6f95ff-73dd-4504-a652-992e3ef6128a"),
                            Name = "HM",
                            Value = 97
                        },
                        new
                        {
                            Id = new Guid("0a410193-e5ec-4067-b2fe-46f13f966cbf"),
                            Name = "VA",
                            Value = 98
                        },
                        new
                        {
                            Id = new Guid("efa35a04-bc59-4a0c-a181-44c22f954aa5"),
                            Name = "HN",
                            Value = 99
                        },
                        new
                        {
                            Id = new Guid("d560eb00-fb3e-4c5a-be15-13da0b4f2280"),
                            Name = "HK",
                            Value = 100
                        },
                        new
                        {
                            Id = new Guid("a43a503c-840d-4982-81cb-f42b1bab2404"),
                            Name = "HU",
                            Value = 101
                        },
                        new
                        {
                            Id = new Guid("9a8cf6ba-94da-45de-b301-0ec67df254f0"),
                            Name = "IS",
                            Value = 102
                        },
                        new
                        {
                            Id = new Guid("52bc4845-7cfb-46b0-8275-30735549fb14"),
                            Name = "IN",
                            Value = 103
                        },
                        new
                        {
                            Id = new Guid("3ce20367-c6ef-46e9-ac57-4960d3a0e918"),
                            Name = "ID",
                            Value = 104
                        },
                        new
                        {
                            Id = new Guid("bb031e07-7567-4706-82d0-59e36283ff41"),
                            Name = "IR",
                            Value = 105
                        },
                        new
                        {
                            Id = new Guid("593db72f-e00c-4165-b851-6bfa6a3cb9c5"),
                            Name = "IQ",
                            Value = 106
                        },
                        new
                        {
                            Id = new Guid("3104518a-cdfc-4e7f-b119-d097b07823e0"),
                            Name = "IE",
                            Value = 107
                        },
                        new
                        {
                            Id = new Guid("d9090e7a-f5ff-458a-85ff-c6c0ce03621e"),
                            Name = "IM",
                            Value = 108
                        },
                        new
                        {
                            Id = new Guid("78e59c2f-e152-468a-afca-ece90faa30be"),
                            Name = "IL",
                            Value = 109
                        },
                        new
                        {
                            Id = new Guid("7fe3f3a2-a7f3-4907-b697-f7375c145824"),
                            Name = "IT",
                            Value = 110
                        },
                        new
                        {
                            Id = new Guid("cd26dc37-5c71-4c2b-8381-e4773a8de36c"),
                            Name = "JM",
                            Value = 111
                        },
                        new
                        {
                            Id = new Guid("a0626187-e2da-4fd9-8935-831a9fe259f8"),
                            Name = "JP",
                            Value = 112
                        },
                        new
                        {
                            Id = new Guid("30846950-595a-4e9d-b2fc-8bd6c5c53309"),
                            Name = "JE",
                            Value = 113
                        },
                        new
                        {
                            Id = new Guid("b0c04434-8af5-4f6e-b19a-297c3738480d"),
                            Name = "JO",
                            Value = 114
                        },
                        new
                        {
                            Id = new Guid("a88565ec-f4f4-4bdf-b647-7cb76ac8301a"),
                            Name = "KZ",
                            Value = 115
                        },
                        new
                        {
                            Id = new Guid("351d2771-8500-4591-a8fc-6518816143b8"),
                            Name = "KE",
                            Value = 116
                        },
                        new
                        {
                            Id = new Guid("2fd8e62d-03f5-43da-a34e-137359b5f82e"),
                            Name = "KI",
                            Value = 117
                        },
                        new
                        {
                            Id = new Guid("1f099d5e-b51c-4a4a-96cb-09f650b19784"),
                            Name = "KP",
                            Value = 118
                        },
                        new
                        {
                            Id = new Guid("38b4ad3a-43ab-4a34-bdc3-99b4afb9c511"),
                            Name = "KR",
                            Value = 119
                        },
                        new
                        {
                            Id = new Guid("576bd41f-ba84-470a-8902-c107faf668eb"),
                            Name = "KW",
                            Value = 120
                        },
                        new
                        {
                            Id = new Guid("d2f948ab-20de-42d1-8db0-669e51f3aff1"),
                            Name = "KG",
                            Value = 121
                        },
                        new
                        {
                            Id = new Guid("11b8d791-3493-4681-907a-ad82f9af7788"),
                            Name = "LA",
                            Value = 122
                        },
                        new
                        {
                            Id = new Guid("beeec53b-77b1-43b9-90cc-afa426e18e80"),
                            Name = "LV",
                            Value = 123
                        },
                        new
                        {
                            Id = new Guid("5857e20a-2b02-4961-b199-376096acc967"),
                            Name = "LB",
                            Value = 124
                        },
                        new
                        {
                            Id = new Guid("3c396e85-4987-4a2b-ad95-093bbce7a83d"),
                            Name = "LS",
                            Value = 125
                        },
                        new
                        {
                            Id = new Guid("83995e4a-0a93-4618-bd7a-9af3ad2717d6"),
                            Name = "LR",
                            Value = 126
                        },
                        new
                        {
                            Id = new Guid("b00c9782-ec3c-49b6-997e-2a91003de297"),
                            Name = "LY",
                            Value = 127
                        },
                        new
                        {
                            Id = new Guid("5c5d6bf6-4b5f-4be6-a698-afcc67dfc839"),
                            Name = "LI",
                            Value = 128
                        },
                        new
                        {
                            Id = new Guid("7f2cce6c-14a5-45e5-8d74-ced2ec9fba65"),
                            Name = "LT",
                            Value = 129
                        },
                        new
                        {
                            Id = new Guid("63733e62-f3ab-42f1-b790-9dcb6970e804"),
                            Name = "LU",
                            Value = 130
                        },
                        new
                        {
                            Id = new Guid("e2245716-ab12-4e14-aaec-f863c245fc9f"),
                            Name = "MO",
                            Value = 131
                        },
                        new
                        {
                            Id = new Guid("03d13902-f1d4-4978-9564-d9c465108eb6"),
                            Name = "MK",
                            Value = 132
                        },
                        new
                        {
                            Id = new Guid("3116f7b1-b6a3-424d-b4ad-e9baf6e225f3"),
                            Name = "MG",
                            Value = 133
                        },
                        new
                        {
                            Id = new Guid("280f3f23-ddf3-4fd9-8eff-b7bf65bc3d63"),
                            Name = "MW",
                            Value = 134
                        },
                        new
                        {
                            Id = new Guid("7fc70a0b-6f50-4c00-bf45-d9610303eea4"),
                            Name = "MY",
                            Value = 135
                        },
                        new
                        {
                            Id = new Guid("8f10a755-2fa7-4dad-a729-d6586fccfae3"),
                            Name = "MV",
                            Value = 136
                        },
                        new
                        {
                            Id = new Guid("df9bb74b-4104-4616-aa51-31ad18086e5e"),
                            Name = "ML",
                            Value = 137
                        },
                        new
                        {
                            Id = new Guid("48a82db3-9186-4e9d-9dfd-a48d74ec05f2"),
                            Name = "MT",
                            Value = 138
                        },
                        new
                        {
                            Id = new Guid("d33dd066-bb1f-4daa-b3dc-037649b1ba67"),
                            Name = "MH",
                            Value = 139
                        },
                        new
                        {
                            Id = new Guid("689bccbe-92b0-4015-af22-e98350c2aac3"),
                            Name = "MQ",
                            Value = 140
                        },
                        new
                        {
                            Id = new Guid("a8589144-6513-47c2-9658-397380b72c3b"),
                            Name = "MR",
                            Value = 141
                        },
                        new
                        {
                            Id = new Guid("ed82ef11-8e97-42f3-ad3d-4f06cf3bf0d5"),
                            Name = "MU",
                            Value = 142
                        },
                        new
                        {
                            Id = new Guid("5bb9d509-028b-4ec5-986a-515ce12520d8"),
                            Name = "YT",
                            Value = 143
                        },
                        new
                        {
                            Id = new Guid("9c2e7670-d853-44ca-b8b7-c2e9ea0a23fa"),
                            Name = "MX",
                            Value = 144
                        },
                        new
                        {
                            Id = new Guid("07de659c-855c-4c15-90ac-e27253f7609f"),
                            Name = "FM",
                            Value = 145
                        },
                        new
                        {
                            Id = new Guid("c02c195b-4ada-42a6-96a1-167e389fadbb"),
                            Name = "MD",
                            Value = 146
                        },
                        new
                        {
                            Id = new Guid("b353fede-3c41-4871-b407-b13aa7eed09d"),
                            Name = "MC",
                            Value = 147
                        },
                        new
                        {
                            Id = new Guid("a41b96bc-adb7-45ac-9fa6-fae98c8de24e"),
                            Name = "MN",
                            Value = 148
                        },
                        new
                        {
                            Id = new Guid("ff7cd1e7-7dc4-42bc-b317-e11eb0de72ff"),
                            Name = "ME",
                            Value = 149
                        },
                        new
                        {
                            Id = new Guid("f81e682b-6896-4539-a72d-933f40ddc71f"),
                            Name = "MS",
                            Value = 150
                        },
                        new
                        {
                            Id = new Guid("cc412306-25e5-4485-b8ed-d975fab708d2"),
                            Name = "MA",
                            Value = 151
                        },
                        new
                        {
                            Id = new Guid("0228f16f-d39f-4ae9-865d-f752b689cdcc"),
                            Name = "MZ",
                            Value = 152
                        },
                        new
                        {
                            Id = new Guid("21490c86-8138-4f69-b7fa-081974a31903"),
                            Name = "MM",
                            Value = 153
                        },
                        new
                        {
                            Id = new Guid("7df689b1-3f69-441e-9242-2e788cc490c2"),
                            Name = "NA",
                            Value = 154
                        },
                        new
                        {
                            Id = new Guid("e8f8f8c4-3a77-4523-9fdb-1e6ff905982a"),
                            Name = "NR",
                            Value = 155
                        },
                        new
                        {
                            Id = new Guid("984086f9-33a0-4717-a357-782c6a9605f4"),
                            Name = "NP",
                            Value = 156
                        },
                        new
                        {
                            Id = new Guid("5ec6c71a-7524-468c-b07a-797efb5f92d4"),
                            Name = "NL",
                            Value = 157
                        },
                        new
                        {
                            Id = new Guid("6f892654-e8ea-4e5a-b826-370595f1d0ad"),
                            Name = "NC",
                            Value = 158
                        },
                        new
                        {
                            Id = new Guid("27124d2e-510f-44ac-b40b-103169c57c29"),
                            Name = "NZ",
                            Value = 159
                        },
                        new
                        {
                            Id = new Guid("bd39592b-206e-4f44-a65e-a006dc19334c"),
                            Name = "NI",
                            Value = 160
                        },
                        new
                        {
                            Id = new Guid("eca3b86b-cec8-49bb-a2a3-cdeed57a7735"),
                            Name = "NE",
                            Value = 161
                        },
                        new
                        {
                            Id = new Guid("ed314697-4bf1-40fc-880e-039cffa977d8"),
                            Name = "NG",
                            Value = 162
                        },
                        new
                        {
                            Id = new Guid("015d81f9-cd67-4191-affb-1363fa40de7d"),
                            Name = "NU",
                            Value = 163
                        },
                        new
                        {
                            Id = new Guid("c02815a6-656c-48d6-afdc-d29ea279257f"),
                            Name = "NF",
                            Value = 164
                        },
                        new
                        {
                            Id = new Guid("89bd87c4-b358-4478-a4da-a137f95adbb2"),
                            Name = "MP",
                            Value = 165
                        },
                        new
                        {
                            Id = new Guid("43dd9739-8275-4429-9f41-ed2f9dcb2e8b"),
                            Name = "NO",
                            Value = 166
                        },
                        new
                        {
                            Id = new Guid("1ddc2881-9b44-40c0-8efe-8cea6acd51e5"),
                            Name = "OM",
                            Value = 167
                        },
                        new
                        {
                            Id = new Guid("33bfb872-7366-4a74-865a-6b74019e71bf"),
                            Name = "PK",
                            Value = 168
                        },
                        new
                        {
                            Id = new Guid("155c2b46-5ce5-43b6-a8e6-9f043e79d7f0"),
                            Name = "PW",
                            Value = 169
                        },
                        new
                        {
                            Id = new Guid("c36e7695-e539-4ee4-861b-9acbb6f931db"),
                            Name = "PS",
                            Value = 170
                        },
                        new
                        {
                            Id = new Guid("46b832e0-ca8b-4e9c-b0d0-d4e0341f6dba"),
                            Name = "PA",
                            Value = 171
                        },
                        new
                        {
                            Id = new Guid("47d57bd7-69d3-4e8d-8fa9-900855c6f5fa"),
                            Name = "PG",
                            Value = 172
                        },
                        new
                        {
                            Id = new Guid("a1e02d2b-4812-4105-bb14-a82b860353e9"),
                            Name = "PY",
                            Value = 173
                        },
                        new
                        {
                            Id = new Guid("f5848f28-d9bf-4f05-94dc-888235bd9601"),
                            Name = "PE",
                            Value = 174
                        },
                        new
                        {
                            Id = new Guid("aaabc17d-43c1-425d-8035-adb8d6c55ee2"),
                            Name = "PH",
                            Value = 175
                        },
                        new
                        {
                            Id = new Guid("4171ad22-24db-49fb-a022-a3a3ce13e75e"),
                            Name = "PN",
                            Value = 176
                        },
                        new
                        {
                            Id = new Guid("32ddf016-e07c-4d6f-84db-3ecb9f7a64cc"),
                            Name = "PL",
                            Value = 177
                        },
                        new
                        {
                            Id = new Guid("c1707bdc-840c-4e3f-9fc8-80691c89c9eb"),
                            Name = "PT",
                            Value = 178
                        },
                        new
                        {
                            Id = new Guid("a156314b-274c-431a-abf8-bb4f7c611d82"),
                            Name = "PR",
                            Value = 179
                        },
                        new
                        {
                            Id = new Guid("0ee4658f-eecd-47d4-864e-ae7f48b120b6"),
                            Name = "QA",
                            Value = 180
                        },
                        new
                        {
                            Id = new Guid("2447aeed-9211-4d1e-9e6d-882be06bdd23"),
                            Name = "RE",
                            Value = 181
                        },
                        new
                        {
                            Id = new Guid("302f3718-aecd-4d09-b7f1-d185d58f1294"),
                            Name = "RO",
                            Value = 182
                        },
                        new
                        {
                            Id = new Guid("f8ac0931-9352-4db0-89b9-a80b83a7f37a"),
                            Name = "RU",
                            Value = 183
                        },
                        new
                        {
                            Id = new Guid("26a5ecf2-f7cb-4a1c-95d1-5439080c2b7b"),
                            Name = "RW",
                            Value = 184
                        },
                        new
                        {
                            Id = new Guid("e3518af7-afa1-4bc5-afef-70676070a925"),
                            Name = "BL",
                            Value = 185
                        },
                        new
                        {
                            Id = new Guid("48654947-7884-497d-ab12-f1340cefcb50"),
                            Name = "SH",
                            Value = 186
                        },
                        new
                        {
                            Id = new Guid("903d0ebd-5a96-465b-a478-ce4d4777d974"),
                            Name = "KN",
                            Value = 187
                        },
                        new
                        {
                            Id = new Guid("c1a84cdb-752e-409d-a326-d202cd0d4a4c"),
                            Name = "LC",
                            Value = 188
                        },
                        new
                        {
                            Id = new Guid("7a0765d0-5073-4946-9b8d-a7e22bf5199b"),
                            Name = "MF",
                            Value = 189
                        },
                        new
                        {
                            Id = new Guid("1dd25007-bac6-4af1-8807-76db580e65ac"),
                            Name = "PM",
                            Value = 190
                        },
                        new
                        {
                            Id = new Guid("dc3c83ac-00ac-484e-a355-90bf3836d6e0"),
                            Name = "VC",
                            Value = 191
                        },
                        new
                        {
                            Id = new Guid("38cc6eb3-da6d-4282-a341-c4c2cd7f700b"),
                            Name = "WS",
                            Value = 192
                        },
                        new
                        {
                            Id = new Guid("b849d2b4-6dda-4a91-a081-7aa08e7ad235"),
                            Name = "SM",
                            Value = 193
                        },
                        new
                        {
                            Id = new Guid("1fd65baa-a9a0-4eb2-a777-1082a1954d2c"),
                            Name = "ST",
                            Value = 194
                        },
                        new
                        {
                            Id = new Guid("c1804492-b37d-49e9-8142-612672f67370"),
                            Name = "SA",
                            Value = 195
                        },
                        new
                        {
                            Id = new Guid("59ee66a8-0506-4fd0-9ba7-a33c2d941b95"),
                            Name = "SN",
                            Value = 196
                        },
                        new
                        {
                            Id = new Guid("f90f92a3-2b7f-4b22-8882-9b28f60fbb2e"),
                            Name = "RS",
                            Value = 197
                        },
                        new
                        {
                            Id = new Guid("59a14fa6-2e4b-4d7f-a748-e84204f5af9a"),
                            Name = "SC",
                            Value = 198
                        },
                        new
                        {
                            Id = new Guid("54e5e330-b8d3-4c4b-9531-90a5a97ffe12"),
                            Name = "SL",
                            Value = 199
                        },
                        new
                        {
                            Id = new Guid("bccc6713-9485-4ef8-bafc-de3f2920504d"),
                            Name = "SG",
                            Value = 200
                        },
                        new
                        {
                            Id = new Guid("6ed5bc2b-605d-4257-9be8-cfe55227d58b"),
                            Name = "SX",
                            Value = 201
                        },
                        new
                        {
                            Id = new Guid("4d7289e1-5a37-4168-92c9-39353382e2d6"),
                            Name = "SK",
                            Value = 202
                        },
                        new
                        {
                            Id = new Guid("29a77941-cdb0-46a5-8f67-4af595e85ec8"),
                            Name = "SI",
                            Value = 203
                        },
                        new
                        {
                            Id = new Guid("03964a61-f40a-4d47-aad4-7554a86dbc41"),
                            Name = "SB",
                            Value = 204
                        },
                        new
                        {
                            Id = new Guid("e90dffea-75af-4bde-9e67-92bdda222670"),
                            Name = "SO",
                            Value = 205
                        },
                        new
                        {
                            Id = new Guid("0c03898f-7483-41ce-b723-d1172b03a210"),
                            Name = "ZA",
                            Value = 206
                        },
                        new
                        {
                            Id = new Guid("849ef571-9544-4afa-9a92-af0208ffca7e"),
                            Name = "GS",
                            Value = 207
                        },
                        new
                        {
                            Id = new Guid("c34fc8d4-c93a-45d3-9c26-c108935e37dd"),
                            Name = "SS",
                            Value = 208
                        },
                        new
                        {
                            Id = new Guid("da00527b-be8c-4514-a921-340cd96985b9"),
                            Name = "ES",
                            Value = 209
                        },
                        new
                        {
                            Id = new Guid("82cb2ae0-6519-4727-b8cd-877abf000453"),
                            Name = "LK",
                            Value = 210
                        },
                        new
                        {
                            Id = new Guid("d0c36ef5-a339-411a-86ba-4c32fa7aa830"),
                            Name = "SD",
                            Value = 211
                        },
                        new
                        {
                            Id = new Guid("ea3e38ef-c2ef-40bd-8b9b-1d2cbeccf6b1"),
                            Name = "SR",
                            Value = 212
                        },
                        new
                        {
                            Id = new Guid("1867979d-3db4-4795-a79c-186db24ce26f"),
                            Name = "SJ",
                            Value = 213
                        },
                        new
                        {
                            Id = new Guid("abccb784-f22b-4b29-87b8-4a1081bfcb35"),
                            Name = "SZ",
                            Value = 214
                        },
                        new
                        {
                            Id = new Guid("16f6c4cd-3d7b-4648-ae8b-f9c7588b44b2"),
                            Name = "SE",
                            Value = 215
                        },
                        new
                        {
                            Id = new Guid("a35441f8-13e2-404f-ad38-e42f0cac0f59"),
                            Name = "CH",
                            Value = 216
                        },
                        new
                        {
                            Id = new Guid("5dc05d2f-440a-4ff1-8520-8f8749ace929"),
                            Name = "SY",
                            Value = 217
                        },
                        new
                        {
                            Id = new Guid("6f15aeae-e1ed-425f-895c-2e74e10671b9"),
                            Name = "TW",
                            Value = 218
                        },
                        new
                        {
                            Id = new Guid("71924ca9-9bec-4a60-9bad-6a1096d20207"),
                            Name = "TJ",
                            Value = 219
                        },
                        new
                        {
                            Id = new Guid("57b56a9c-fe4b-4759-aff7-2212bf14a7c5"),
                            Name = "TZ",
                            Value = 220
                        },
                        new
                        {
                            Id = new Guid("88b2870e-4207-48df-bc31-0435f44d7e3f"),
                            Name = "TH",
                            Value = 221
                        },
                        new
                        {
                            Id = new Guid("3e43967e-6104-431c-8079-73130054040b"),
                            Name = "TL",
                            Value = 222
                        },
                        new
                        {
                            Id = new Guid("9c852227-41ac-4f49-afbe-27c6869648ec"),
                            Name = "TG",
                            Value = 223
                        },
                        new
                        {
                            Id = new Guid("c54bb71a-04f0-48f7-8fd7-072f4ca28869"),
                            Name = "TK",
                            Value = 224
                        },
                        new
                        {
                            Id = new Guid("067d029f-3386-4cf6-936e-42b3c6700d9a"),
                            Name = "TO",
                            Value = 225
                        },
                        new
                        {
                            Id = new Guid("631bd74a-698f-4bc5-b8e5-877f66011fcd"),
                            Name = "TT",
                            Value = 226
                        },
                        new
                        {
                            Id = new Guid("4350e755-fe34-45fb-997c-1411f29afb71"),
                            Name = "TN",
                            Value = 227
                        },
                        new
                        {
                            Id = new Guid("04dda2ed-04fb-4045-a4f4-f8fe1263680f"),
                            Name = "TR",
                            Value = 228
                        },
                        new
                        {
                            Id = new Guid("0fd9c9ce-5d19-4f18-b4b0-eaa98fa4962c"),
                            Name = "TM",
                            Value = 229
                        },
                        new
                        {
                            Id = new Guid("041a73c1-94e4-40b5-be2b-a7104815727b"),
                            Name = "TC",
                            Value = 230
                        },
                        new
                        {
                            Id = new Guid("32d2a6b7-32a5-498b-9ea4-e4a22a2d7493"),
                            Name = "TV",
                            Value = 231
                        },
                        new
                        {
                            Id = new Guid("3d6477de-7e24-43f5-a615-7a3d28fc6992"),
                            Name = "UG",
                            Value = 232
                        },
                        new
                        {
                            Id = new Guid("be8727d6-856e-4de2-bc95-65bf19fb191f"),
                            Name = "UA",
                            Value = 233
                        },
                        new
                        {
                            Id = new Guid("71f70988-0b5a-46be-9019-32c8ced442f9"),
                            Name = "AE",
                            Value = 234
                        },
                        new
                        {
                            Id = new Guid("e2e334c7-caab-4151-a9b3-1eb5b32c5f4c"),
                            Name = "GB",
                            Value = 235
                        },
                        new
                        {
                            Id = new Guid("bb7e7d49-1fb0-4f70-8129-ee5e6d6ccd53"),
                            Name = "US",
                            Value = 236
                        },
                        new
                        {
                            Id = new Guid("93a0c180-1f30-4638-ae48-fb8085162638"),
                            Name = "UM",
                            Value = 237
                        },
                        new
                        {
                            Id = new Guid("f0b716d7-c0b0-4d1d-92a5-27c5eee0f61a"),
                            Name = "UY",
                            Value = 238
                        },
                        new
                        {
                            Id = new Guid("223b254e-84c2-41ef-a368-9c81800d66e9"),
                            Name = "UZ",
                            Value = 239
                        },
                        new
                        {
                            Id = new Guid("f78824ba-afc6-411a-b79e-e5051d449970"),
                            Name = "VU",
                            Value = 240
                        },
                        new
                        {
                            Id = new Guid("8f0f1646-4395-402c-9818-d3ace985b33b"),
                            Name = "VE",
                            Value = 241
                        },
                        new
                        {
                            Id = new Guid("f712485d-e5de-4620-be5b-fa9cec50220a"),
                            Name = "VN",
                            Value = 242
                        },
                        new
                        {
                            Id = new Guid("0b34c110-1742-42a4-876d-c81c68877838"),
                            Name = "VG",
                            Value = 243
                        },
                        new
                        {
                            Id = new Guid("26d1c0e5-1628-48ff-87d1-fc2b12d107f4"),
                            Name = "VI",
                            Value = 244
                        },
                        new
                        {
                            Id = new Guid("328de1e9-05c1-47cc-8fc9-ddc823009173"),
                            Name = "WF",
                            Value = 245
                        },
                        new
                        {
                            Id = new Guid("3d219530-b74a-4bb3-bdd1-bc240286300b"),
                            Name = "EH",
                            Value = 246
                        },
                        new
                        {
                            Id = new Guid("14148840-50f1-413c-9149-bbffe2446e13"),
                            Name = "YE",
                            Value = 247
                        },
                        new
                        {
                            Id = new Guid("4dea1eb7-b158-4d63-9d8f-47c2f35346bb"),
                            Name = "ZM",
                            Value = 248
                        },
                        new
                        {
                            Id = new Guid("d274458d-38b5-4be9-b5cc-58dbf450139a"),
                            Name = "ZW",
                            Value = 249
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MachineDimensionsType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d06bf4d7-0c13-4e54-9dbc-29a71bd3566c"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("7ed8b1da-76b4-4df3-b855-3098084329ba"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("cf8646b4-4ecc-400d-8ca7-43354c400e34"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MillingMachineType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8fb70dd-0328-4dac-bde3-d0f4c7f39dc0"),
                            Name = "TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("b9a8edbb-6ca8-45a1-b7a5-c721f29ab9ed"),
                            Name = "TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("0981aff6-3416-4537-867f-6c621ecd430b"),
                            Name = "TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("0842591e-6e18-47e4-9a8c-e2665aeea558"),
                            Name = "TYPE_4",
                            Value = 3
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("OtherTechnology");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a13cd35a-95cb-462b-8ac7-81e8705f547b"),
                            Name = "DeepHoleDrilling",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("d1c1681e-b8c4-4045-b29f-ce466e599798"),
                            Name = "ThreadsM",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("b7841423-e53e-4941-bd86-2ac869fd34fd"),
                            Name = "ThreadsTr",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("5dea6de7-cb25-49ee-bd13-4ff64e1beb98"),
                            Name = "Toothings",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("f90c523e-9d77-44c1-a85d-6d4de47519ab"),
                            Name = "Engravings",
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("46d90eb7-53b4-43b0-b6a8-f712b5e00aed"),
                            Name = "LaserMarking",
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("c8725c85-e9bc-414e-85b7-68194ca6476c"),
                            Name = "Knurling",
                            Value = 6
                        },
                        new
                        {
                            Id = new Guid("6b9d9c37-fd40-4f2e-a157-53867298b90e"),
                            Name = "Annealing",
                            Value = 7
                        },
                        new
                        {
                            Id = new Guid("29f26969-90b3-4001-9dee-5aac967c9f36"),
                            Name = "Other",
                            Value = 8
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("MillingMachineDimensionsTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MillingMachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MillingMachineDimensionsTypeId");

                    b.HasIndex("MillingMachineTypeId");

                    b.ToTable("MillingMachine");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("MillingMachineDimensionsType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6058ea0-2c0e-4beb-9bc0-bbc64e1ea742"),
                            Name = "THREE_AXIS",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("1cf9aa5d-64c1-4332-b4c8-97b91315723b"),
                            Name = "THREE_PLUS_TWO_AXIS",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("a7e598dc-6225-4db3-bd2b-46822d2b11dd"),
                            Name = "FIVE_AXIS",
                            Value = 2
                        });
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("MachineNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<int>("MinimalMachiningDimensions")
                        .HasColumnType("int");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TurningMachineTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TurningMachineTypeId");

                    b.ToTable("TurningMachine");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.TurningMachineType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Value");

                    b.ToTable("TurningMachineType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("771fc31a-b10d-4f29-8afc-c55a2e31cd8b"),
                            Name = "TURNING_MACHINE_TYPE_1",
                            Value = 0
                        },
                        new
                        {
                            Id = new Guid("9b9111a4-cab6-4521-88c5-083288bd1774"),
                            Name = "TURNING_MACHINE_TYPE_2",
                            Value = 1
                        },
                        new
                        {
                            Id = new Guid("67b10097-cb9f-4fe2-aeb5-d93420e805a7"),
                            Name = "TURNING_MACHINE_TYPE_3",
                            Value = 2
                        },
                        new
                        {
                            Id = new Guid("91832b1e-615b-4dc2-b5a4-a398e732bee4"),
                            Name = "TURNING_MACHINE_TYPE_4",
                            Value = 3
                        },
                        new
                        {
                            Id = new Guid("23884dbd-9f04-4348-9191-b266096da30e"),
                            Name = "TURNING_MACHINE_TYPE_5",
                            Value = 4
                        });
                });

            modelBuilder.Entity("CertificationCustomer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Certification", null)
                        .WithMany()
                        .HasForeignKey("CertificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerOtherTechnology", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.Technologies.OtherTechnology", null)
                        .WithMany()
                        .HasForeignKey("OtherTechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Address", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.AddressType", "AddressType")
                        .WithMany()
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CountryCodeType", "CountryCode")
                        .WithMany()
                        .HasForeignKey("CountryCodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddressType");

                    b.Navigation("CountryCode");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.CompanySizeType", "CompanySizeType")
                        .WithMany()
                        .HasForeignKey("CompanySizeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanySizeType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithOne("CustomerAdditionalInfo")
                        .HasForeignKey("Oroox.SubSuppliers.Domain.Entities.CustomerAdditionalInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.MillingMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("MillingMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.MillingMachineDimensionsType", "MillingMachineDimensionsType")
                        .WithMany()
                        .HasForeignKey("MillingMachineDimensionsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Enumerations.MillingMachineType", "MillingMachineType")
                        .WithMany()
                        .HasForeignKey("MillingMachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MillingMachineDimensionsType");

                    b.Navigation("MillingMachineType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.TurningMachine", b =>
                {
                    b.HasOne("Oroox.SubSuppliers.Domain.Entities.Customer", "Customer")
                        .WithMany("TurningMachines")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oroox.SubSuppliers.Domain.TurningMachineType", "TurningMachineType")
                        .WithMany()
                        .HasForeignKey("TurningMachineTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("TurningMachineType");
                });

            modelBuilder.Entity("Oroox.SubSuppliers.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CustomerAdditionalInfo");

                    b.Navigation("MillingMachines");

                    b.Navigation("TurningMachines");
                });
#pragma warning restore 612, 618
        }
    }
}
